openlibhums/janeway

src/core/workflow.py

While loading Kanban with fresh install without any plugin, and load the Kanban Page, it raises Error.
Finding out more, it seems like `AttributeError` is not cached.

Fixing AttributeError for Kanban

---

src/events/logic.py
src/journal/models.py
src/journal/views.py

Please check to make sure I'm setting things up correctly. Added an event for when an article is marked as published, and a staticmethod to the Issue class that generates the next logical volume and issue numbers based on the last released (non-collection) issue. If there are no issues, it returns (1, 1).

Add publication event, auto-increment method to journal.models Issue

---

.gitignore

Current defaults in the makefile create a file called `db/janeway.sqlite`, without the `3` suffix. This file ought to be ignored by git.

gitignore all .sqlite* files

---

src/submission/admin.py

Closes #626 
Related issue to limit the license list in Admin: https://github.com/BirkbeckCTP/janeway/issues/713

Label for license updated to just the shortname.

---

src/journal/urls.py
src/journal/views.py
src/themes/default/templates/journal/authors.html

#748 
This creates a view function to see all authors of a journal from the front end and then gives the option to link to their public profile if it is enabled. So a view for an author that shows the list of published articles as I described in the original issue is not necessary.

add author view, url and template

---

src/core/janeway_global_settings.py
src/core/templatetags/fqdn.py
src/journal/models.py
src/press/models.py
src/templates/admin/preprints/author_article.html
src/templates/admin/press/press_manager_index.html
src/themes/OLH/templates/core/base.html
src/themes/OLH/templates/journal/article.html
src/themes/OLH/templates/press/press_journals.html
src/themes/default/templates/core/base.html
src/themes/default/templates/journal/article.html
src/themes/material/templates/core/base.html
src/themes/material/templates/journal/article.html
src/utils/install/journal_defaults.json

Fixes #790 
It modifies an entry in `janeway_global_settings.py` that is probably currently overriden in 1.3.1 installations.
In #787 I'm looking at improving the new settings loader to merge certain settings types instead of just overriding them, which should make it possible to expand janeway_global_settings without requiring changes onto 1.3.1  `settings.py` files

Improvements to the new Journal.site_url function

---

src/templates/admin/journal/sitemap.xml

Closes #802
There were a couple other badly formatted article URLs

#802: Fixes article URLs with double base URLs

---

docker-compose.yml
dockerfiles/Dockerfile

Just add the python packages under janeway/lib/ and they will get installed in the janeway docker image when running `make rebuild`.
Libraries are isntalled in development mode, changes to the local libraries will reflect on the running containers withouth having to re-run `make rebuild`

Allows installation of local python packages

---

src/core/migrations/0019_adds_DomainAlias_journal_FK.py

The custom SQL can't be reverted with django.db.backends.postgresql as the whole migration runs within an atomic block.

Fixes migration 0019 for postgres

---

src/themes/OLH/templates/journal/authors.html
src/themes/default/templates/journal/authors.html
src/themes/material/templates/journal/authors.html

I was missing these in my initial PR. remedying that now with styles that match the editorial_team.html for both those themes. Also, made the default template file a little more legible with white space.

add OLH and material themes templates for author list 

---

src/review/forms.py
src/review/views.py
src/templates/admin/review/notify_reviewer.html
src/utils/forms.py
src/utils/tests.py

Closes #848 
Adds a preview of the inline review form as well as a link to download the file within a foundation accordion:

review form preview

---

src/review/views.py

use files.delete_file(article,file) instead of file.delete() from core.files.py to unset file from article when author is performing a revision. 
file is still available in document manager.

use method to unlink file from article, not delete file

---

src/templates/admin/production/assigned_article.html

replaced the direct --article_file_make_galley button to convert file to html via pandoc.

convert copyedited files in typesetting/production

---

src/core/middleware.py
src/core/model_utils.py

- Fixes relative emails sent for settings stored in the Press as attributes
- Fixes a bad url on the press base template when calling press.site_url with `path=None`

1.3.3 minor fixes

---

src/templates/admin/elements/issue/table_of_contents.html
src/templates/admin/journal/manage/issue_add_article.html

This adds a column to the issue ToC and add_article interface in the issue manager so that editors can sort by the article date submitted.
This is particularly helpful when using the [archive plugin](https://github.com/dSHARP-CMU/archive_plugin) when you need to select between multiple article versions with the same title.

Display article sub. date on issue manager

---

src/themes/OLH/templates/elements/journal/box_article.html

Closes #998 
An erroneous hide class was hiding this element.

#998 removes hide class"

---

src/press/models.py
src/themes/OLH/templates/journal/homepage_elements/journals.html
src/themes/OLH/templates/press/press_journals.html
src/themes/default/templates/journal/homepage_elements/journals.html
src/themes/material/templates/journal/homepage_elements/journals.html

remove deprecated `full_url` for `site_url`. remove port handling in template of press_journals in OLH.
BTW, I noticed no `/templates/press/press_journals.html` for default or material themes.

journal link via press determined on DEBUG in settings.

---

Makefile
dockerfiles/Dockerfile
dockerfiles/Dockerfile.base

The python:3.5.4 docker image is now stale. I've changed the docker files to use the latest python:3.5 image instead. (it also upgrades pip to the latest version).

Bump python to 3.5:latest on base docker image

---

requirements.txt

I tested the playground on `django-summernote` 0.8.11 and it does solve this issue, which was solved in summernote itself: https://github.com/summernote/summernote/pull/2933
closes #1028

#1028: Bumps django-summernote (adds relative links)

---

.update.sh

- Install requirements should happen before invoking `python manage.py`
- Changes the command for loading new settings to use the new one.

Updates upgrade script for 1.3.4

---

src/journal/logic.py

Adds `BASE_DIR/files/styling/journals/default/` to the scss for each journal, allowing to declare custom default css overrides for all the journals in the installation.

Adds support for a default override.scss

---

src/journal/logic.py
src/themes/OLH/build_assets.py
src/themes/OLH/templates/core/base.html

Previous implementation of SCSS default override would ignore journal specific overrides.
Now both will be processed correctly and imported in the template in the right order

Fixes default SCSS override behaviour

---

src/proofing/views.py

Spent a bit of time on this one, everything seems to work fine and I was able to upload a new galley on every new round of proofing.
That said, without this change it was impossible to see them on the dashboard!
Closes #1138

#1138: Changed permissions on proofreader dashboard

---

src/journal/models.py
src/journal/views.py
src/themes/OLH/templates/journal/issue_display.html
src/themes/default/templates/journal/issue_display.html
src/themes/material/templates/journal/issue_display.html

A few improvements here:
- Merges Issue and Collection views onto a single view (some optimizations were present on one and not the other)
- Stops using `Issue.structure` in this view and marks it as deprecated. (We need to preserve the interface for other themes)
- Adds a new method to `Issue` `get_sorted_articles` which returns all the articles sorted by section and article order, ready to be displayed on the frontend.
- The articles are paginated when an issue has at least 50 articles

1136 performance improvements

---

src/core/middleware.py
src/utils/logger.py

Fixes a memory leak with the new logger introduced in 1.3.5 when dispatching multiple requests on a single thread.

Fix logger leak

---

src/themes/default/templates/core/nav.html
src/themes/default/templates/elements/article_listing.html
src/themes/material/templates/elements/article_listing.html

when using a non standard port the article view links in the default and material themes are missing the port number resulting in a 404
same for the search box in the default theme

fix articles links and search box when using non standard ports

---

requirements.txt

@mauromsl can you review this and move the 1.3.5 tag up?

Bumps Django due to security vulnerability.

---

src/utils/models.py

Currently, If the import cache files have been cleared from an install, all the import commands stop working as they try to clear the cache themselves.

`ImportCacheEntry.nuke` to handle FileNotFoundError

---

src/core/logic.py
src/templates/admin/review/add_files.html
src/utils/install/journal_defaults.json

If default_review_visibility is set to blind or double-blind we recommend the editor ensures the files are anonymised.
This closes #1187

1187 added new text setting and checkbox.

---

src/core/plugin_loader.py
src/core/tests/test_plugins.py

Raises an error at loading time when a plugin is found to be incompatible with the current janeway version

Validate plugin version

---

src/core/views.py
src/themes/OLH/templates/core/accounts/activate_account.html
src/themes/default/templates/core/accounts/activate_account.html
src/themes/material/templates/core/accounts/activate_account.html

Closes #578.
This update prevents browser pre-loading from triggering the completion of registration.

#578 completing the registration process now requires clicking a button.

---

src/core/forms.py
src/core/logic.py
src/proofing/models.py
src/proofing/views.py
src/templates/admin/core/manager/index.html
src/templates/admin/proofing/proofing_article.html
src/utils/install/journal_defaults.json

Added settings to limit the number of proofreaders by round.

---

src/templates/admin/copyediting/add_copyeditor_assignment.html
src/templates/admin/copyediting/copyediting.html
src/templates/admin/core/active_submissions.html
src/templates/admin/core/dashboard.html
src/templates/admin/core/nav.html
src/templates/admin/elements/core/kanban/card.html
src/templates/admin/elements/core/submission_list_element.html
src/templates/admin/elements/production/card.html
src/templates/admin/elements/proofing/add_proofreader.html
src/templates/admin/elements/proofing/card.html
src/templates/admin/journal/manage/archive.html
src/templates/admin/journal/manage/issues.html
src/templates/admin/journal/publish.html
src/templates/admin/production/assign_typesetter.html
src/templates/admin/production/assigned_article.html
src/templates/admin/review/add_files.html
src/templates/admin/review/unassigned.html

Makes changes requested in issue #1343

---

src/core/homepage_elements/journals/hooks.py
src/core/homepage_elements/journals/plugin_settings.py
src/core/homepage_elements/journals_and_html/forms.py
src/core/homepage_elements/journals_and_html/hooks.py
src/core/homepage_elements/journals_and_html/plugin_settings.py
src/core/homepage_elements/journals_and_html/templates/journals_and_html.html
src/core/homepage_elements/journals_and_html/urls.py
src/core/homepage_elements/journals_and_html/views.py
src/core/models.py
src/themes/OLH/templates/press/homepage_elements/journals_and_html.html
src/themes/default/templates/press/homepage_elements/journals_and_html.html
src/themes/material/templates/press/homepage_elements/journals_and_html.html

Added a new homepage element for Journals and HTML block.

---

src/press/views.py
src/themes/OLH/templates/journal/homepage_elements/about.html

1357 press logo fixes

---

src/journal/management/commands/galley_healthcheck.py

```
root@898c7f34bbb4:/vol/janeway# python src/manage.py galley_healthcheck --help
usage: manage.py galley_healthcheck [-h] [--version] [-v {0,1,2,3}]
[--settings SETTINGS]
[--pythonpath PYTHONPATH] [--traceback]
[--no-color]
[journal_codes [journal_codes ...]]
Checks the health of all the published article galleys
positional arguments:
journal_codes
```

Command that runs a galley healthcheck

---

src/core/file_system.py

Fixes the problem were running the development server from a different path than `settings.BASE_DIR` would break the JanewayFileSystemStorage.

JanewayStorage can determine relative paths dinamically

---

requirements.txt

https://github.com/BirkbeckCTP/janeway/network/alert/requirements.txt/Django/open

Bump django version for CVE-2019-19844

---

src/templates/admin/production/assigned_article.html

These buttons were the wrong way round. Data/Images should not have it and all other file types should.

Swapped around the make galley button. Closes #1360.

---

src/core/logic.py

Handle CMYK images

---

src/journal/models.py

closes #1307 
closes #1179
If the sections within an issue are lacking or have identical
SectionOrder.order or Section.sequence values, they will now be sorted
by PK, avoiding the repeated sections problem

Adds section PK to issue articles ordering logic

---

src/journal/urls.py
src/journal/views.py

1515 added a new view that returns XML if an article has an XML galley.

---

src/security/decorators.py

It also moves the redirect logic to the base_check function itself with a decorated decorator pattern.
closes #1546

Fixes security base_check redirects for path mode

---

src/core/models.py
src/core/tests/test_app.py
src/core/tests/test_models.py

#1497: Fix bad normalisation on Account.email

---

src/core/migrations/0039_fix_reviewer_url.py

Fixes a problem with core 0039
I found this to only be a problem on the demo site, so might be only an issue with mysql or perhaps something to do with how settings were handled in a different version. Anyways, good to have

Handle migrating non-string values (i.e.: NULL)

---

src/submission/models.py
src/submission/tests.py

The original fix for #1565 wasn't handling corporate authors

#1565: Handle Corporate authors

---

src/templates/admin/elements/fundref/fundref.html

Probably an oversight when running in dev mode

#1451: Fix mixed-type request to xref API

---

src/core/models.py

Some plugins were having trouble with the previous implementation, throwing a two-step transaction was not a good decision.
Now that I think of it, I don't understand why this is the default behavior in django itself

#1497: Fixes a race condition on Account create

---

src/core/files.py

When we parse the XML galleys into a python unicode string, the processing instructions get corrupted (never terminate) which leads to an error when later transforming the galley via XSL.
Checking on the acta repo, I believe we souped the xml to do this:
```
xml = BeautifulSoup(xml_file_contents, ["lxml", "xml"])
if galley:
elements = {
'graphic': 'xlink:href'
}
for element, attribute in elements.items():
images = xml.findAll(element)
for image in images:
image['xlink:href'] = "/article/{0}/galley/{1}/figure/{2}".format(
article.pk,
galley.pk,
os.path.basename(image['xlink:href']))
```
But that code was later removed in this commit:
```
commit 584382dd5bf1c2ce095b526112d9227f6f544f1e
Author: Martin Eve <martin@martineve.com>
Date:   Sun Feb 26 16:13:39 2017 +0000
Add TEI rendering
Rewrite …
```

Stops tampering XML during XSL transform

---

src/themes/OLH/assets/scss/app.scss

I played around with the opacity, but it makes the Issue details barely readable and highly dependent on the choice of cover image.I think making the info-bar relative to the image is a better choice
Result:

Fix info-bar covering issue cover

---

src/core/files.py
src/core/models.py
src/journal/logic.py
src/journal/views.py
src/production/views.py
src/templates/admin/proofing/preview/rendered.html

- On article view, gets the best render possible for the syntax errors given on the source XML
- On article preview view, shows only the rendering errors.
closes #1623

Improvements to render error handling on XML galleys

---

src/journal/tests/test_models.py

- Replace 'otherjournal' with 'oj' in all values in test_models.py
- fixes #1635

Truncate test_model.py values to be less than 15 characters

---

src/submission/forms.py
src/submission/views.py

- Adds an optional boolean kwarg `backend` to `submission.forms.ArticleInfo`.
- If set to True this will stop the form from over-writing metadata with the defaults set in the submission configuration tool.
Closes #1642

#1642 Adds an option backend kwarg to ArticleInfo form.

---

src/review/logic.py

closes #1646 
It looks convoluted, but without calling values on the column we want to group by, the default behaviour is to group by the wrong column, leading to multiple rows being returned from the subquery. Sometimes I wish I could just write SQL...

Fixes wrong group by on subquery

---

src/transform/xsl/default.xsl

closes #1650 
Bonus Track: Renders child uri elements of mixed-citation tags as hyperlinks

Fixes XSLT links to mixed-citation elements from inline citations

---

src/submission/models.py

1692 marks self.journal.name as safe in article.how_to_cite

---

src/review/views.py

Closes #1696 
- Staff permissions are not required to edit review forms - its expected that editors would do this.
@mauromsl can you review this before we do the RC8 release?

#1696 updated decorator on edit review forms views.

---

src/journal/models.py
src/themes/material/assets/mat.css
src/themes/material/templates/journal/issues.html

On material, adds a fancy overflow for journals that render long issue titles with volume/issue/year
closes #1689

Change of approach for issue page layout

---

src/submission/models.py

Mitigates #1666 
- The issue and volume were the wrong way around (my bad!)
- Issues `Article.issue` instead of `Article.primary_issue` to be consistent with the citations rendered on the citation styles menu.

Fixes issue details on how to cite

---

src/core/views.py

closes #1706 
Its just a patch for v.1.3.8-RC-8, the real solution should be #1708

#1706: Fix settings reverted when disabling submissions

---

requirements.txt

Pins geoip2 version for py3.5 compatibility

---

src/core/templatetags/hooks.py

Also changes changed the exception level to `Exception` for reasons previously discussed.

Use logger for hook rendering errors

---

src/core/files.py

A fix for installs that use different devices to store article/journal files
On python 3 `shutil.move` handles moving files across devices by falling back to `.copy` and `.remove` when necessary

Fix cross-device move on save_file_to_article

---

src/core/models.py
src/core/tests/test_app.py
src/core/tests/test_validators.py
src/core/validators.py
src/core/views.py

closes #1722 
This just addresses the current problem, which is good for patching 1.3.8, but moving forward we might want to transition this view to use a proper form and have the validation logic

validate email setting value

---

src/transform/xsl/default.xsl

This is the recommendation from crossref. With this change,
we render pub-ids of pub-id-type doi as a hyperlink when they are
in URL format. Otherwise, we preserve the legacy format of
doi: [shoulder/id]

[XSLT] Render pub-id URLs as hyperlinks

---

src/core/janeway_global_settings.py
src/identifiers/models.py
src/journal/logic.py

I've also added a timeout in the new DOI status poll view.
We should probably hunt down all the other outgoing http requests and set the timeout to `settings.HTTP_TIMEOUT_SECONDS`

Fixes timeout errors during prepub

---

src/repository/admin.py
src/repository/views.py
src/static/common/css/repo.css
src/static/common/js/material-eq-height.js
src/themes/material/templates/repository/elements/preprint_home_listing.html
src/themes/material/templates/repository/home.html

- Adds an HR to seperate the Search from Submit sections
- Limits the homepage preprints to 6 (maybe should be a setting in future releases)
- Adds some common JS to make material rows and cols equal height. This exists already for BS and Foundation.

Updates the homepage of the material theme.

---

src/themes/OLH/templates/repository/nav.html
src/themes/material/templates/repository/nav.html

add capfirst builtin to repository list navigation in OLH and Material theme repository nav templates

---

src/press/models.py
src/templates/admin/repository/log.html
src/templates/admin/repository/manager.html

The main log entry page is now more verbose. Im not sure how I feel about this but we'll see.
Closes #1773

1773 log page

---

src/core/urls.py

Fixes the infamous error `django.urls.exceptions.NoReverseMatch: 'djdt' is not a registered namespace` in the simplest way possible.

Ensure debug toolbar urls loaded during testing

---

src/repository/views.py

Issue - UI page states that the list of publication is in the order published but that is not the case.
Fix - added order_by publication date
Views affected - list all publications and home page list the latest

Added order_by publication date for list and home page view

---

src/themes/material/templates/core/base.html
src/themes/material/templates/repository/base.html
src/themes/material/templates/repository/preprint.html

I added an un-related commit that fixes a broken download link in the preprint template

[Preprints] minor template bugs - fix escaping for custom_js and broken download link

---

src/core/models.py
src/journal/views.py
src/review/views.py
src/submission/logic.py
src/submission/models.py
src/submission/tests.py
src/submission/views.py

Fixes a couple of problems:
- Frozen author metadata was being overridden when calling `article.snapshot_authors`. There is now a `force_update` flag to control this behaviour.
- Refactored the function to iterate the authors in `article.snapshot_authors` so that authors without an `ArticleAuthorOrder` record are not ignored

Stop overriding frozen author records at publication time

---

src/themes/material/templates/repository/list.html
src/themes/material/templates/repository/preprint.html

‘login’ should be ‘log in’ in the sentence “You must login to post a comment.”

[Preprints] minor tweaks to minor improvements #1834

---

src/repository/logic.py
src/repository/management/commands/generate_preprints.py
src/repository/views.py
src/templates/admin/repository/manager.html

This PR:
- Removes the First Author from New and Published Preprints
- Removes the Views and Downloads from Published Preprints
- Reduces the number of queries from 2480 to 15.
The solution is just a suggestion, instead we could limit the number of Published preprints to say 100 and add a search option.
Comments welcome @justingonder @hardyoyo @tingletech

1842 admi dash load

---

src/templates/admin/elements/metadata.html
src/templates/admin/identifiers/manage_identifier.html
src/templates/admin/journal/manage/archive_article.html

Bonus Tracks:
- Adds a more prominent alert and a link if an article has no DOI
- Adds a sample DOI based on pattern on new DOI view
closes #1764

Removes duplicate Identifiers block in article archive view

---

src/core/logic.py
src/templates/common/elements/guest_editors.html
src/themes/OLH/templates/elements/journal/article_issue_list.html
src/themes/OLH/templates/elements/journal/issue_top.html
src/themes/default/templates/elements/journal/article_issue_list.html
src/themes/default/templates/elements/journal/issue_top.html
src/themes/material/templates/elements/journal/issue_top.html
src/utils/install/journal_defaults.json

- Adds a new setting to the Article group, display_guest_editors
- Displays a primary issue's guest editors if it has any
Closes #1285

#1285 guest editors now display, optionally, on the article page.

---

src/repository/views.py

Description: Hello,
I seem to be having trouble accessing the moderation part of the EA
dashboard. I can access the repository manager no problem; however, if I
try to access X Versions Awaiting Moderation or View Orphaned Preprints, I
encounter the following:
```
You are authenticated as ____, but are not authorized to
access this page. Would you like to login to a different account?
```
Any advice would be appreciated.

[preprints] links on repository manager dashboard should work

---

src/themes/material/templates/repository/list.html

Replaces `preprints | length` with the actual count of objects in the paginator object (working back from the paginator.page object, held by 'preprints' on the repository list.html template. Fixes #1871.

use the count of objects from the paginator.page object for the list of preprints

---

src/core/logic.py
src/themes/OLH/templates/journal/submissions.html
src/themes/default/templates/journal/submissions.html
src/themes/material/templates/journal/submissions.html
src/utils/install/journal_defaults.json

Since this setting is used also in the homepage element, editors can't leave it  blank in order to remove it from the submissions page but not the front page.
I added a bool setting to control this instead.

Optional about block on submissions page

---

src/core/forms.py
src/core/views.py

With the message we currently have, some users give up on re-trying /resetting their password and contact support thinking their account does not exist.
The new message doesn't reveal any details about the account while pointing out that the password might be wrong. This is relevant particularly for authors that publish papers for more than one journal in a given press.

Make it more clear that the credentials might be wrong

---

src/core/files.py

Fixes #1874 
Mitigates a bug where replaced files such as manuscripts were being cached by the browser.
Chrome and Firefox will ignore the cache-control directive when making the same request from the same tab, so the only way to reproduce the bug originally reported is to:
- Download a file.
- Replace the file.
- Download the file again from a different tab.
I've taken an abrupt approach in that I've removed the cache-control header from all `serve_ file_to_browser` requests (except images) but perhaps a more selective approach might be best, knowing that cache invalidation is the hardest problem in computer science ;)
Any thoughts @ajrbyers  ?

Removes cache-control header from file serving

---

src/submission/logic.py
src/submission/tests.py
src/submission/views.py

- Handles missing author role logic in `logic.add_user_as_author` (controlled via `kwarg`)
- Removes the various pieces of logic for adding paper authors from the `submit_authors` view and calls `logic.add_user_as_author` instead.

Automatically give author role to assigned authors

---

src/repository/models.py

- adds the user's orcid to the author dictionary for new authors
- updates the author object with the user's orcid to catch an edge case
fixes #1878

Add Self as Author button: ensure the user's orcid is copied, too

---

src/core/migrations/0042_auto_20200825_1051.py

Simplifies the logic for handling duplicate usernames and fixes a bug were if the first username of a matching set was mixed case the operation was ignored

#1838: Refactor core 0042 migration

---

src/core/logic.py
src/templates/admin/review/review_form.html
src/utils/install/journal_defaults.json

- Adds a new setting `peer_review_upload_text`
- Setting is displayed on the Review Settings page
- Displays text above the Upload File box on the Peer reviewer form page
Closes #1921

#1921 adds new peer review setting for the upload box description.

---

src/journal/views.py

Closes #1946
search: the sniper irish short
before this pr = `'^(short\\|the\\|irish\\|the\\ sniper\\ irish\\ short\\ story|story|sniper\\)`
after this pr = `'^(short|the|irish|the\\ sniper\\ irish\\ short\\ story|story|sniper)`

Fix regex escaping during search term split

---

requirements.txt

As documented on [HackerNews](https://news.ycombinator.com/item?id=25145396) the Pip package manager for Python recently had its dependency algorithm tweaked. This lead to a situation where the current requirements.txt file could not be used with the latest version of pip without the load of dependencies failing. This change bumps up the version for the requests package to a version that keeps the current pip happy. Tests pass with this version of the library.

bump requests to 2.25.1 to make current pip happy

---

requirements.txt

Latest version breaks backwards compatibility with 1.11:
https://github.com/django-hijack/django-hijack/issues/223

Pin django-hijack for 1.11 compatibility

---

src/templates/common/apis/OAI_record.xml
src/templates/common/apis/OAI_record_header.xml

- Fixes a bug where the publication year was wrong.
- Changes the <dc:date> to an ISO 8601 date
closes #2012

Fix wrong type for dc:date on OAI

---

src/themes/material/assets/mat.css
src/themes/material/templates/repository/list_subjects.html

closes #2029 
I can't verify that this works well with the subjects, not sure if this feature was ever completed.
It does however resolve the larger problem with the dropdowns as per #2029

Better CSS selector for subjects' <ul>

---

src/repository/models.py
src/templates/admin/elements/repository/version_detail.html
src/templates/admin/repository/article.html
src/templates/admin/repository/version_queue.html

----
fixes some errors on `preprints-remodel` that were keeping us from pushing the latest changes.
Justin reported on https://github.com/BirkbeckCTP/janeway/issues/1873#issuecomment-741984981
I think we have not pushed code to prod since before  #1891 ?
yea, our prod is running c1e628c5c92bec288580278d4e544fa8b941a66e right now
---
I kept getting different errors between dev and localhost, after some false leads, turned out it was because debug mode made the error manifest differently.  Tried `path` and `host` modes and different versions of python before I figured out it was debug mode that was making me not be able to reproduce the same exact errors.

[preprints] Preprint remodel metadata edit bug

---

src/submission/models.py
src/templates/common/elements/how_to_cite.html
src/utils/importers/shared.py

Adds page numbers to the "how to cite" block when they are available
Also a  fix to the shared importer when handling the new KeywordArticle model

How to cite page numbers

---

src/templates/admin/repository/article.html

The heading 'delete' in the Pending Updates table is incorrect as the actions in that column are 'Manage' not 'Delete.' Changing heading to 'Manage.'

Correct Pending Updates table heading

---

src/journal/views.py

Noted after migrating the OLH journal.
Collections are createdin advance of receiving any articles, which leads to them being rendered as empty collections on the site

Exclude empty collections

---

src/review/logic.py
src/review/views.py
src/templates/admin/review/add_review_assignment.html
src/utils/install/journal_defaults.json

Now:
1. You can enter an email + acc. Doesn't matter if they already exist or aren't enrolled or anything. It finds existing users. Tries to enroll them if not enrolled. Or creates the account.
2. Then when you return to the enrollment page, some on_ready JS does an auto datatables search for the account you just entered, and then ticks the checkbox for you
Closes #1968

Improvements to the peer review assignment workflow in one-click mode.

---

src/core/views.py
src/templates/admin/core/manager/email/email_templates.html

Closes #2146 
The edit email setting link was pointing to the email setting name rather than the subject setting name

#2146: Fix broken link to edit email subjects

---

src/journal/models.py
src/utils/transactional_emails.py

When a revision request has no editor assigned no email notification was sent
Now we fallback to article editors -> journal editors

Revision request for missing editors

---

src/review/forms.py

The frontend allows editing part of the review assignment form when it is accepted, but the form itself still has those fields set as required leading to the review assignment not getting updated and the user receiving no feedback on the error

Fix edit accepted assignment

---

src/themes/OLH/templates/core/accounts/register.html
src/themes/material/templates/core/accounts/register.html

The logic to load custom journal privacy policy URLs was missing on this page

Update privacy-policy URL in registration pages

---

.gitignore
Makefile
db/pgadmin/.gitignore
db/pgadmin/servers.json
docker-compose.yml

A pgadmin container will be run and automatically connect to the postgres container when using postgres as your DB_VENDOR

Add pgadmin to docker-compose stack

---

src/templates/admin/elements/metadata.html

They can edit metadata, but they don't have a link to the page atm

Render 'Edit metadata' link to section editors

---

src/journal/logic.py
src/utils/notify_helpers.py

v1.3.10-RC-1 changed the signature of send `send_email_with_body_from_user` and some callers were now sending the log_dict as the CC field.

Fix bad function signature

---

src/review/views.py
src/templates/admin/elements/review/decision_form_modal.html
src/templates/admin/elements/review/review_file_table_modal.html
src/templates/admin/review/decision_helper.html
src/templates/admin/review/view_review.html

- Tells the editor which review comments won't be displayed to the author.
- Tells the editor if the review file will be avialble to the author
- Allows the editor to control review file visibility from the decision helper

Flag hidden comments

---

src/utils/importers/up.py

Handles cases where we can't match a license url in the souped content

Fix UP import with no license

---

.lando.yml
requirements.txt

Django 1.11.x fails to connect to PostgreSQL databases when using psycopg2 2.9 onwards, due to a failing timezone-related assertion.
This also moves from psycopg2 to psycopg2-binary for Lando, which should have no external effect.
Closes #2274.

Pin psycopg2-binary to ~2.8.0

---

src/core/migrations/0001_initial.py
src/core/models.py

'Mx' is the most predominantly used gender-neutral title, and is widely accepted by organisations, including the UK Government.
This PR makes Janeway systems slightly more inclusive.
See [the Wikipedia article](https://en.wikipedia.org/wiki/Mx_%28title%29) for more information.

Add 'Mx' as a salutation

---

src/security/logic.py
src/templates/admin/journal/file_history.html

Backports the three commits from https://github.com/BirkbeckCTP/janeway/pull/1925 to the preprint-remodel branch, which is due to be merged soon, but we happen to have preprint-remodel deployed to production, and would feel more comfortable using an official branch than a bespoke one.

Hotfix PUBD-209 section editors should be able to download assigned files

---

.lando.yml

- Utilize the new `dir` config for Lando tooling, and drop the fragile pipefitting that was in place before
- Add a runserver restart tooling command, to quickly restart the runserver, and also access the debug interface.

Update the Landofile for Janeway

---

src/cms/migrations/0005_auto_20210518_1619.py

Migration now uses `translation.override` when creating SubmissionItems.
Closes #2316

#2316 use translation.override to create SIs

---

src/review/views.py
src/security/decorators.py
src/static/admin/css/admin.css
src/templates/admin/elements/article_jump.html
src/templates/admin/review/home.html
src/templates/admin/review/in_review.html

- Disabled the review header link when an article is unassigned
- If somehow an editor makes it review there is now a callout warning (image below), this only works for articles in the Unassigned stage.
- Warning messages are now improved
Closes #2315

2315 bugfix

---

src/journal/models.py
src/submission/models.py
src/submission/tests.py

When the issue volume/number is set to zero, avoid displaying it.
It doesn't make the fields optional yet as per #2337, but I'm not sure defaulting to zero when a value is not provided makes a lot of sense. what do you think @ajrbyers

2337 issue volume zero

---

src/themes/material/assets/mat.css
src/themes/material/assets/material.js
src/transform/xsl/default.xsl

Closes #2399 
Bonus:
- Smooth scrolling on relative urls for material
- Fix article `<ol>` tags rendering as `<li>`

Fix wrong offset on footnote relative links

---

src/themes/OLH/templates/journal/article.html
src/themes/clean/templates/journal/article.html
src/themes/material/templates/journal/article.html

Also, avoid rendering isntitution when its value is `" "`

Fix: render orcid when article images are disabled

---

src/review/views.py
src/templates/admin/review/add_review_assignment.html

Removes the Assign with Defaults button as Editors seem unable to resist clicking it without checking what it does in the documentation.

Drop Assign with Defaults button

---

src/static/OLH/css/app.css
src/themes/clean/templates/cms/page.html
src/themes/material/assets/mat.css
src/themes/material/templates/cms/page.html

Closes #2435 
Updated material to use a H1 for its cms/page.html. Tweaked some CSS to make the balance better. Screenshots of an example page for each theme below.

#2435 rebalanced headers.

---

src/templates/admin/repository/article.html

11:47 AM alainna ah, I've found an unexpected issue with the "View live article" link on the dashboards - link will display even if the preprint hasn't yet been published, but only on the moderator's side.

check is_published for View Article moderator page (preprint-merge)

---

src/templates/admin/repository/author_article.html

The Author_article template currently does not mention DOIs at all, #2188 implies that it should. This commit ports the new logic from the author.html template to author_article.html.

Add DOI and Preprint DOI to Author_Article template

---

src/utils/install/journal_defaults.json

The description for the email template and subject used in the event that a reviewer declines a review invitation mistakenly had the language "agree to undertake" rather than "decline to undertake."

Fixing typo in declination email template, subject description

---

src/utils/management/commands/load_default_settings.py

- Can be used thus: `python3 src/manage.py load_default_settings --force_update`
- Closes #2620

#2620 added a --force_update flag to load_default_settings

---

src/transform/xsl/default.xsl

- Adds array
- Adds tbody
- Adds H2 ID too app title
- Removes `<br>` and `<small>` from comments
- Closes #2587 
_Note_: Some of these changes were present in my default 1.4 but not in default.xsl so added them here.

#2587 updated xslt

---

src/transform/xsl/default.xsl

Fixes an issue where the footnote number calculator was considering table footnotes which led the links in the footnotes to not match to be offset by the total number of table footnotes available in the body.
closes #2680

#2680: XSLT fix fn links colliding with tables

---

src/themes/material/templates/core/accounts/public_profile.html

Without this, the profile images can overflow beyond their column, sometimes spanning across the entire profile page

Makes profile image responsive on material

---

src/themes/OLH/templates/journal/article.html

The drilldown menu for citations on small screens didn't work properly, because there isn't enough space to render all the submenu options.
I've changed it to a regular dropdown menu instead, as with the medium/large screens.

OLH: Changes citation picker to a dropdown on mobile

---

src/utils/management/commands/install_janeway.py

During install, I had `make install` failing on `janeway-web` with an error such as:
```python
...
File "/vol/janeway/src/utils/management/commands/install_janeway.py", line 85
journal.domain = input('Journal #1 domain: (Optional)')
^
IndentationError: unexpected indent
```

wrong indentation and typo

---

src/utils/forms.py
src/utils/tests.py

Prevent empty keywords from being saved when using KeywordModelForm

---

src/api/oai/base.py
src/api/oai/views.py
src/api/tests/test_oai.py
src/utils/http/__init__.py

closes #2768 
Also adds a journal context filter lost with 251e4d1

OAI resumptionToken now considers querystring params

---

src/utils/forms.py
src/utils/tests.py

Resolves a bug introduced in 0c38a3fd59725429cba34458636cae87322ea4df due to a pointless overprotective feature

Fixes Keywords not saving due to cleaned data not being mutable

---

src/core/include_urls.py
src/core/templatetags/pages.py
src/core/views.py
src/templates/admin/core/article_list.html
src/templates/common/elements/pagination.html

Here is the work in progress for the CBV base class. I've put it on core and chosen a url and template name ('article_list`) that will work well with the default naming conventions of CBVs in later versions of Django.
I also implemented pagination via a template element, forming the template so it works with existing CSS.
What else should be included at this stage, before we create more specialized views?

Add base class for filterable class-based view

---

src/submission/forms.py
src/templates/admin/elements/metadata.html
src/templates/admin/submission/edit/metadata.html

Allows Competing Interests to be edited from the Edit Metadata pane. Also tidies up the View Metadata and Edit Metadata pages to correspond to each other more closely with peer review status and page numbers. Fixes #2735.

Allows Competing Interests to be edited from the Edit Metadata pane

---

src/journal/migrations/0047_issue_code.py
src/journal/models.py

Default max key size for MySQL indexes is 3072 bytes (768 characters * 4 bytes with UTF-8 encoding)
closes #2905

Adjusted Issue.code so it can be indexed by MySQL

---

src/transform/xsl/default.xsl

#2651 JATS: <title> tags inside a glossary now output as an H2

---

src/core/model_utils.py
src/submission/models.py
src/utils/management/commands/generate_search_indexes.py

Due to limitations of the ORM, we have to run raw SQL in order to both run a distinct query on article hits AND be able to sort by relevance

Allow search results to be orderered by relevance (Postgresql)

---

src/themes/OLH/templates/core/accounts/reset_password.html
src/themes/clean/templates/core/accounts/reset_password.html
src/themes/material/templates/core/accounts/reset_password.html

Fixes: #2972 by copying password rules from the registration page to the reset password page

#2972 move password rules markup from register to reset_password templates

---

src/core/migrations/0074_fix_editorial_images_group.py
src/utils/install/journal_defaults.json

The group name for the styling settings had been changed correctly in the code and with a migration, however the
journal_defaults.json file not been updated for two of them due to a bad merge.
This PR changes the group and runs a migration to fix installations that may have been created AFTER the migration had already run. It also cleans up installations that had migrated correctly but would have a ghost setting with the wrong group as a result of updating the default settings
Closes #3006

Fixed a server error when opening the Styling menu on the manager

---

src/submission/views.py
src/templates/admin/elements/submission/additional_fields.html
src/templates/admin/submission/edit/metadata.html
src/templates/admin/submission/submit_info.html

#2986 when editing an articles metadata the additional field options will now be also editable.

---

requirements.txt

It was actually a bug with the `django-materialize` library that we have fixed here: https://github.com/BirkbeckCTP/django-materialize/commit/97328e75a6ae723eff1035dd553a29e33a4ce530
This PR only bumps the version of django-materialize
Closes #2991

Fixed an issue where filter toggles where not retained after running a search

---

src/templates/admin/repository/article.html

Does this work to enable both moderators and super users/staff to un-reject preprints? Only preprint moderators should be able to access this page, no? 
https://github.com/BirkbeckCTP/janeway/issues/2539

Enable preprint moderators to un-reject preprint

---

src/core/files.py

#3109 full text indexing will now work as expected for documents with a <body> tag.

---

src/journal/logic.py
src/journal/models.py
src/templates/admin/elements/publish/issues.html
src/themes/OLH/templates/elements/journal/article_issue_list.html
src/themes/clean/templates/elements/journal/article_issue_list.html

In addition to the logic changes specified in the bug description, I've made the primary issue visible on the modal:
I've also added "Primary" before the primary issue in the OLH and material theme sidebars for consistency, since we prepend the name of the issue type (e.g. "Collection" or "Issue") for subsequent issues in the issue list).

Fix logic on issue assignment during prepublication checklist

---

src/themes/OLH/templates/journal/homepage_elements/featured.html
src/themes/OLH/templates/journal/homepage_elements/popular.html
src/themes/clean/templates/journal/homepage_elements/featured.html
src/themes/clean/templates/journal/homepage_elements/popular.html
src/themes/material/templates/journal/homepage_elements/featured.html
src/themes/material/templates/journal/homepage_elements/popular.html

Closes #2460 and closes #3075:
- Includes large image of issue as fallback on popular and featured homepage elements
- Makes disabling article images work in featured and popular elements

Bugfixes for popular and featured homepage elements

---

docs/source/published/articles.rst
src/events/logic.py
src/events/registration.py
src/journal/views.py
src/review/urls.py
src/review/views.py
src/submission/models.py
src/templates/admin/journal/manage/archive_article.html
src/utils/install/journal_defaults.json

The button appears at the bottom of the Article Archive page.
Fixes #2859.
Editors can draft an email to the author, much like they can when accepting or declining an article.

Add Undo Article Rejection button on archive page

---

src/transform/xsl/default.xsl

This was fixed in #2681 but accidentally lost in f0ff0bf7ca39fdf49f7483df9ef06ba76f599f7d

Fix an issue where table footnotes would lead article footnotes to no longer link correctly

---

src/core/workflow.py

Closes #3059 
**Note:** we are aware that this does not work for Production Managers in the old Production Proofing workflow, this is a limitation that cannot be handled at the moment.

3059 when an editor completes a workflow element they will automatically be moved onto the next one rather than being directed to the dashboard

---

src/core/models.py
src/templates/admin/journal/document_management.html
src/templates/admin/production/assign_typesetter.html
src/templates/admin/production/assigned_article.html
src/templates/admin/production/edit_galley.html
src/templates/admin/production/edit_typesetter_assignment.html
src/templates/admin/production/typeset_task.html
src/templates/admin/proofing/proofing_article.html
src/templates/admin/proofing/request_typesetting_changes.html
src/templates/admin/review/unassigned_article.html

- Swaps date_modified for last_modified across the core
- Adds a date_modified property for backwads compat
- PR added to Typesetting where this is used extensively: https://github.com/BirkbeckCTP/typesetting/pull/165
- Closes #2904

#2904 fixes an issue that caused modified dates for File objects not to show up

---

docs/source/manager/articlesissues/index.rst
src/submission/models.py
src/submission/tests.py

Fixes #3130.
When the First Page field is populated but no other page number field, the number will now properly display in the Issue table of contents.

Fixes a bug with page ranges that caused articles not to appear in lists

---

src/submission/tests.py

Some IDs were hard-coded so the test failed when other tests run before it.

Fix test_article_image_galley

---

.update.sh

- uses the [unofficial Bash strict-mode](http://redsymbol.net/articles/unofficial-bash-strict-mode/) settings
- underlying errors now cause the .update.sh script to fail
- fixes #3190

3190 Use unofficial Bash strict-mode in .update.sh

---

src/core/include_urls.py
src/core/views.py
src/templates/admin/core/manager/plugins.html

An error is displayed listing all plugins that are installed on the database but have failed to load.
Additionally, during startup, all kinds of load errors are now handled and logged properly

Allow plugins page to render even when plugins fail to load

---

src/utils/transactional_emails.py

New preprint submission notices should reference Repository, not Press

New preprint submission references Repository

---

src/themes/material/templates/core/accounts/reset_password.html

I think it's because we are accessing an object attribute from the `blocktrans` [block](https://docs.djangoproject.com/en/1.11/topics/i18n/translation/#blocktrans-template-tag).
It probably happens in many other forms also.
For completeness, django 4.1 uses the tag [`blocktranslate`](https://docs.djangoproject.com/en/4.1/topics/i18n/translation/#blocktranslate-template-tag) (instead of `blocktrans`).

Password length not showing in pwd reset form

---

requirements.txt
src/core/views.py
src/utils/orcid.py

closes #3243 
- When logging in with ORCiD for the first time, if an account already exists in Janeway it is linked automatically
- When logging in with ORCiD for the first time, if an account does not exist in Janeway, we pre-fill the form with data from ORCiD API.
- Users registering using the login with orcid function don't need to activate their account (as long as they use their verified oricd email address)

Simplified flow for first-time ORCID login

---

src/core/plugin_loader.py

So that django apps (i.e. not Janway plugins) can register their own hooks.
This is the same as PR #2941 (unfortunately I wasn't able to just re-open the old one).

Isolate code that loads hooks.

---

src/templates/admin/elements/core/submission_list_element.html

This PR:
- Swaps our homegrown truncate tag for django's `truncatechars_html` which will close any open tags before truncation
- Ups the character limit to 200, roughly three lines of title
Closes #3278

#3278 fixed a bug on Active Submissions caused by unclosed html tags during truncation.

---

src/templates/admin/elements/metadata.html

When an article has had several reviews completed, but it is not yet accepted or declined, this new text will more clearly explain the status to authors.

#3284 Clarify template text for peer review status during review

---

src/identifiers/logic.py
src/identifiers/tests/test_logic.py

Adds a unit test to ensure we have coverage both for the setting being on and off
Fixes #3293

Fixes a bug where Issue DOI auto-assignment could not be disabled when enabling Crossref

---

src/core/janeway_global_settings.py

Add pagination for Django REST Framewark, so that all API endpoints paginate their results.

Add pagination for Django REST Framework to Janeway global settings

---

src/themes/material/templates/repository/nav.html

- Missing ! causes the link not to work.
- Closes #3302

#3302 hamburger menu now works on Repository mobile interface.

---

src/core/templatetags/debug_tools.py

`ModuleNotFoundError` is the correct exception raised in this scenario

Handle error when nose is not present

---

src/api/urls.py
src/api/views.py
src/templates/common/apis/redoc.html
src/templates/common/apis/swagger_ui.html

These dynamically-generated API docs are helpful when working with building out the API. The spec version has been set to 0.0.1 to make clear this is a draft API.

Add swagger and redoc docs to api

---

src/utils/notify_helpers.py
src/utils/notify_plugins/notify_email.py
src/utils/transactional_emails.py

There have been reports of editors accidentally including authors onto communications amongst editors, as a result of editors replying to the submission acknowledgement email which comes from a Janeway configured email address but has the author as the Reply-To header.
By removing the header, editors can still reply (Other editors are cc'ed in) and discuss amongst themselves without accidentally including the author

Author address won't be shared as reply-to on submission acknowledgements

---

src/templates/admin/repository/manager.html

- Add template fragment cache around metrics block on repository/manger template
- fixes #3309

3309 Add template fragment cache to metrics block on /repository/manager

---

src/repository/logic.py
src/templates/admin/repository/manager.html

closes #3309 
pre-calculates the author name for each preprint at the database, avoiding potentially thousands of roundtrip requests to the database to fetch the related author data

Improved performance of repository manager page

---

src/templates/admin/elements/article_jump.html

This view has been protected by `@editor_user_required` for a while so has been available for editors to use if the know the path. Editors want to make use of the archive function that appears on this view so we should make the page available.

The manage workflow stage link is now available to editors

---

src/api/tests/test_oai.py
src/api/tests/test_preprint_oai.py
src/templates/common/apis/OAI_preprint_record_jats_stub.xml
src/templates/common/encoding/article_jats_1_2.xml

fixes #3361 
- On journal articles, author email addresses will only be marshalled following correspondence author logic
- On Preprint articles, no author emails are marshalled

Fixed an issue where author emails were being exposed via OAI unintentionally

---

requirements.txt
src/templates/admin/core/manager/settings/edit_setting.html

In this PR I've switched us over to a production version of Django Bootstrap 4. This version and the version we were using have a common ancestor and other than bootstrap_icon being deprecated are compatible and render the same but the newer version works with Django 3.2+.

Switched to a production version of django-bootstrap4

---

src/utils/install/licence.json

I think that the wording for the Creative Commons license "No Derivatives" (ND) has changed from NoDerivs in [3.0](https://creativecommons.org/licenses/by-nd/3.0/) to NoDerivatives in [4.0](https://creativecommons.org/licenses/by-nd/4.0/)

Name of CC *-ND licenses changed to NoDerivatives

---

src/api/tests/test_oai.py
src/api/tests/test_preprint_oai.py
src/core/homepage_elements/carousel/tests.py
src/core/tests/test_models.py
src/submission/tests.py

The tests currently issue a number of warnings about "naive datetimes" ... warnings are distracting. This pull request eliminates them by using timezone.make_aware and timezone.datetime, to work with built-in methods for Django to generate datetimes with expected timezone information.

Refactor tests to eliminate naive datetime warnings

---

src/journal/models.py
src/utils/function_cache.py

Copes with the changes introduced in https://github.com/django/django/commit/06076999026

Fixes mutable_cache_property for django 3.2

---

src/api/oai/base.py

- Adds a time bound to the until date string if until is present in the OAI query. This makes the filter inclusive of the until date.

#3420 adds time 23:59:59 to the oai feed until date when present

---

src/core/logic.py
src/templates/admin/elements/forms/group_journal.html
src/themes/OLH/templates/journal/contact.html
src/themes/clean/templates/journal/contact.html
src/themes/material/templates/journal/contact.html
src/utils/install/journal_defaults.json

- Adds a new setting called contact_info
- Replaces the old attribute on Contact page which is now defunct
- Closes #3428

#3428 revives the contact_info attrbiture as a Setting and uses it on the Contact page.

---

src/templates/admin/copyediting/author_update_file.html
src/templates/admin/review/revision/replace_file.html

- Removes the Continue button (as per #3230)
- Renames the Upload button to Upload and Continue (as per #3230)
- Additionally updates the Copyedit replace file screen (this template appears to be a copy of the revise one and even had a broken title, which has been fixed)
- Makes both of these interfaces similar in layout
- Updated guide text which was specific to Chrome (Firefox says "Browse" Chrome says "Choose file" so its now generic)
- Closes #3230

#3230 removes broken button on revision and copyedit replace file screens

---

src/utils/migrations/0030_upgrade_1_5_0.py

@joemull noted he was seeing a multiple leaf nodes error when running `migrate` for 1.5. I saw this also this morning.

Tweaks utils.0030 to avoid multiple leaf nodes error

---

src/utils/middleware.py

The new BaseMiddleware was ignoring potential returned `HttpRequest` by the legacy `process_request` methods

Fixes an issue with redirection from middleware in Django 3.2

---

src/utils/notify_plugins/notify_email.py

Resolves a problem in Django 3.2 where MAIL FROM values with invalid characters would raise an exception.
I ported the logic from django 1.11 where the email will still be sent with the correct email address, rather than throwing an error to the end-user. We might want to clean up the invalid characters instead, after I'm done reading the 95 pages of RFC 5321...

Pre-sanitize MAIL.FROM before sending notifications

---

requirements.txt
src/core/model_utils.py
src/core/plugin_loader.py
src/janeway/__init__.py
src/utils/logic.py

Due to how Janeway versioning currently works, it is impossible to upgrade Janeway and plugins at the same time (see #3462 for context)
The version should live statically in the codebase rather than just in the database. This PR does still preserve those models so that version changes can still be tracked.
It also makes use of the semver library rather than parsing version numbers ad-hoc during startup checks
closes #3462

Fixes a number of issues with Janeway version missmatches

---

src/security/logic.py

Fixes a 500 raised error when a galley has no file associated with it

---

requirements.txt

These libraries are updated to account for the changed location of `collections.abc`:
```diff
-jsmin==2.2.1
+jsmin==3.0.1
-libsass==0.11.1
+libsass==0.22.0
-python-docx==0.8.6
+python-docx==0.8.11
```
They all support Python 3.6-3.10. The `jsmin` library only has a major version number change because it drops support for Python 2.

Update requirements for Python 3.10 compatibility #3524

---

src/themes/material/templates/journal/contact.html

Recaptcha templatetag loading has been removed in https://github.com/BirkbeckCTP/janeway/issues/1683 but the templatetag call must be removed too

Remove recaptcha_init templatetag

---

docs/requirements.txt

- without the pinning, the Makefile throws errors
- pin jinja2 to 2.11.3
- pin markupsafe to 2.0.1

Update docs/requirements.txt to pin a few module versions

---

Makefile
docker-compose.yml
src/core/dev_settings.py
src/core/janeway_global_settings.py
src/utils/notify_plugins/notify_email.py

With this PR we always sanitize the from address before handing it over to the email backend. This will be a redundant call for some backends but will stop the bad encoding on others.
It also avoids sending an empty reply_to header as some **very** old SMTP servers could have trouble with this.
As a bonus, I added an additional service to docker-compose that allows running the development server against a very simple SMTP server when using the `DEBUG_SMTP` flag (e.g: `DEBUG_SMTP=1 make run`
closes #3545

Fixed an issue where From address was being encoded as a tuple on some email backends

---

src/templates/admin/elements/metadata.html

- Removed edit link from author view, reworded it for editor view
- - Hidden the add DOI button from authors
- Added a status for when a DOI has not been deposited
- Fixes #3502

#3502 DOI edit and add buttons will no longer be shown to authors on the article metadata page. Text on the identifiers section has also been updated

---

src/core/model_utils.py
src/journal/models.py
src/press/models.py
src/repository/models.py

What it says on the tin, it avoids having the development environment render links with the https scheme, which cannot be loaded by django's development server

Disable is_secure URL builder checks when DEBUG is on

---

docs/source/manager/other/index.rst
src/cron/migrations/0001_initial.py
src/cron/migrations/0004_auto_20210831_1159.py
src/cron/models.py
src/templates/admin/cron/manage_reminder.html
src/templates/admin/cron/reminders.html
src/templates/admin/elements/cron/reminders_help.html

3427 automated reminder help text has been update to make the function of the Review (Accepted) review type clearer

---

.update.sh
src/cron/management/commands/install_cron.py

Crontab might be missing from certain environments (especially local developer environments). This PR makes running install_cron optional, and dependent on the existence of /usr/bin/crontab. Warns if the file isn't found.

Add a test for whether /usr/bin/crontab exists, before attempting to run install_cron. Warn if crontab not found.

---

src/core/locales/fr/LC_MESSAGES/django.po
src/submission/migrations/0040_article_projected_issue.py
src/submission/migrations/0042_auto_20200423_1534.py
src/submission/models.py
src/templates/admin/elements/metadata.html
src/templates/admin/elements/summary_modal.html
src/templates/admin/production/assign_typesetter.html
src/templates/admin/review/projected_issue.html

The issue described in #2750 has likely been fixed, but in investigating it, I found a bug in the View Metadata modal that meant users could not change Projected Issue after it was set, because they were sent to the Issue Manager instead of the Projected Issue assignment form.
I changed the link to the correct form, but I did not want to get rid of the link between View Metadata and the Issue Manager, because even if it was the "wrong" link, some people might be using it to manage primary issue assignment before pre-publication. So I added a table for Primary Issue to View Metadata below Projected Issue, and I clarified the text around these forms so that new editors could more easily get up to speed on the difference between Projected and Primary and manage both flexibly.
Closes #2750

Issue assignment clarity

---

src/repository/views.py

#3563 Repository search now uses the account names/institution for search

---

src/utils/admin_utils.py
src/utils/tests.py

Fix bug that prevented BookLink from loading in admin

---

src/themes/material/assets/mat.css
src/themes/material/templates/core/base.html

Fixes a bug where the footer in material theme would not be fixed at the bottom of the page

---

Makefile
src/core/dev_settings.py
src/core/janeway_global_settings.py

When using the docker development setup, and when the `JANEWAY_EMAIL_BACKEND` is present but not set, our `dev_settings.py` file would set the EMAIL_BACKEND to ''

Fixes an issue were email settings were empty on Docker

---

src/templates/admin/repository/manager.html

https://github.com/BirkbeckCTP/janeway/issues/3509 
Removing the "Incomplete submissions" option from the Repository Manager preprints stats box. The link isn't functional, and the information is irrelevant (no one needs to know the count of draft preprints authors haven't yet submitted).

Remove "Incomplete submissions" from repository manager

---

src/review/forms.py
src/review/views.py

- This bug was introduced in 1.5.1
- PR includes a tweak to ensure that the review form preview view takes `disable_reviewer_recommendation` into account
- Closes #3618

#3618 the review preview form now renders correctly accounting for display settings

---

requirements.txt
src/core/janeway_global_settings.py
src/journal/forms.py
src/themes/OLH/templates/journal/full-text-search.html
src/themes/clean/templates/journal/full-text-search.html
src/themes/material/assets/mat.css
src/themes/material/assets/material.js
src/themes/material/templates/500.html
src/themes/material/templates/core/accounts/register.html
src/themes/material/templates/core/accounts/reset_password.html
src/themes/material/templates/core/base.html
src/themes/material/templates/core/nav.html
src/themes/material/templates/elements/nav_element.html
src/themes/material/templates/journal/articles.html
src/themes/material/templates/journal/contact.html
src/themes/material/templates/journal/full-text-search.html
src/themes/material/templates/press/nav.html
src/themes/material/templates/repository/nav.html
src/utils/forms.py

Closes #3425
This morning we discussed potentially keeping this out of 1.5.1 in case there are problems with custom CSS that different journals have implemented using selectors from Materialize 0.100.2. 
Based on the [v1 upgrade guide](https://github.com/Dogfalo/materialize/blob/v1-dev/v1-upgrade-guide.md), there are only a few classes and attributes that are likely to need attention. The following were all changed one-to-one:
`dropdown-button` was changed to `dropdown-trigger`
`button-collapse` was changed to `sidenav-trigger`
`side-nav` was changed to `sidenav`
`data-activates` was changed to `data-target`
When we release this upgrade, we should encourage press managers to check their custom stylesheets for any affected selectors and to change them to the new ones.

Upgrade materialize

---

src/core/forms.py
src/templates/admin/core/manager/notifications/manage_notifications.html
src/templates/admin/elements/forms/group_field.html

This monkey patch is now removed, it was only being used by the `manage_notification` view really. All others had moved to using widgeth attrs.
Closes #870

#870 removed the is_checkbox monkey patch

---

src/utils/management/commands/install_janeway.py

- Add arguments for the install_janeway command for press_name, press_domain, press_contact, journal_name, journal_description, journal_code, journal_domain
- Use environment variables for default values
- Hard code the existing default values into the getenv method invocation for each env, so the script behaves the same as previous versions of Janeway

Use environment variables for defaults for the install_janeway management command

---

src/submission/fields.py
src/submission/forms.py
src/submission/models.py
src/submission/tests.py

- Adds a new method to section that returns a display name for editors that includes information on public submission status
- Adds a new field that displays the above method as the <option> label
- Adds help text explaining that editors will see all sections but that authors will not
- Adds two tests to check that what editors and authors see
- Closes #3652 
Editor view:

#3652 when an editor views the submission form they will now see information about which sections are not open for public submission.

---

src/templates/admin/elements/article_jump.html
src/templates/admin/journal/manage/archive_article.html

I think we need to consider whether article's `url` method should return the `remote_url` when it and `is_remote` are set, but it might have a large impact that needs to be considered.
Closes #3630

3630 the Live Article link in LDM will now link to the remote url when is_remote and remote_url are set

---

requirements.txt

closes #3213
pdfminer is no longer maintained, but there is a well-supported community fork with a fix for our problem and some other benefitial updates

Bump pdfminer to fix bug with blank password on PDFs

---

src/submission/models.py

#3716 next_workflow_element will no longer error out when an article is published.

---

src/submission/views.py
src/templates/admin/elements/submission/edit_author.html
src/templates/admin/submission/edit/metadata.html

- `review.views.edit_metadata` now checks for a query string parameter `modal` so that we can link directly to this page and open an empty author modal
- This fixes an issue where after clicking the Edit button on an author and clicking Add New would cause the form to show the author instance
- Closes #3724

#3728 when editing a frozen author record the Add Author button now works as expected.

---

src/identifiers/logic.py
src/metrics/admin.py
src/production/views.py
src/templates/common/identifiers/crossref_component.xml
src/templates/common/identifiers/crossref_doi_batch.xml

```
<timestamp>20230918114200656</timestamp>
```
- Output remains in the same format but uses server time rather than the user's timezone. Example output from the view above.
- Note this particular example has a timestamp suffix '656' tagged onto it.
- Closes #3486

#3486 DOI batch deposit timestamps are now generated in the view using datetime rather than the now templatetag which uses timezone.

---

src/themes/material/templates/elements/journal/issue_top.html
src/themes/material/templates/journal/article.html
src/themes/material/templates/repository/preprint.html

Tagging @MartinPaulEve who might appreciate this. Thanks for reporting it :)

Removed light and wave effects from headers in the material theme. These serve no real purpose and stop users from copying the title text easily.

---

src/themes/material/templates/journal/article.html

- Adds the required embed js that was missing from the material article template.

Altmetric badges will now display as expected on the material theme.

---

src/review/logic.py

If a reviewer has been assigned a new review, has accepted it but has not completed it that value is left empty but the None still shows up as the "Last Review Completed" for their last review on the Add Review Assignment page.
Some of the None values are there because an article was rejected/archived but that particular person did not leave their review. It also shows None when that person has an active review. But "Last Review Completed" implies that it should show the last review regardless of their current status.
This fix excludes reviews that have null values and shows the actual last date of a completed review. 
I don't know if it would be better code-wise to explicitly state that you want to hide articles that are in `STAGE_REJECTED` in addition to hiding NULL values or if there …

prevents None from appearing in Add Review Assignment

---

src/submission/forms.py

- Updates the ORCID regex utility to allow only 0 or 9 in the fourth position of the first block
- Updates error message to have more information about valid ORCID patterns
- Closes #3638

3638 orcid pattern update

---

src/submission/models.py
src/templates/admin/review/home.html

This is far from out perfect solution (using citeproc for example), but a general complaint we've had during the aperio migration is that authors names should be joined by a comman except for the last author which should be an ampersand.

Updates how_to_cite generation.

---

src/static/clean/css/clean.css
src/themes/clean/assets/css/clean.css
src/themes/clean/templates/journal/editorial_team.html

Bootstrap's built-in card deck is fairly unpredicatable and only works for one row so I've removed it in favour of just making use for the grid and a class to force cards to be full-size, which gives better results.
Closes #3802 
NB. This has been deployed to Amherst here: https://openpublishing.library.umass.edu/cpo/editorialteam/

#3802 rework the clean theme's editorial page layout.

---

src/submission/forms.py

3828 EditorArticleInfoSubmit now checks if the section field is present before altering it.

---

src/core/logic.py
src/utils/notify_plugins/notify_email.py

Retrieve press-level email subjects from settings #3694

---

src/journal/views.py

Important: Please don't merge this in v1.5.1! It could introduce further bugs in the press-level templates that we haven't caught because Janeway was using the journal-level templates. Let's introduce it in v1.5.2 or later.
Closes #3709.

Use press-level contact template at press level #3709

---

src/core/forms/forms.py
src/core/locales/cy/LC_MESSAGES/django.po
src/core/locales/de/LC_MESSAGES/django.po
src/core/locales/en-us/LC_MESSAGES/django.po
src/core/locales/fr/LC_MESSAGES/django.po
src/core/locales/it/LC_MESSAGES/django.po
src/core/locales/nl/LC_MESSAGES/django.po
src/core/migrations/0001_initial.py
src/core/migrations/0074_account_suffix.py
src/core/models.py
src/core/views.py
src/journal/migrations/0026_journal_keywords.py
src/journal/models.py

Copyediting related to press site #3711

---

src/press/models.py
src/press/views.py

Completes #3707.
The new `public_journals` method did not take `sequence` into account. This PR updates the method and uses it for the `journals` view, avoiding repetition of logic.

Make journal sorting more reliable

---

src/templates/common/elements/edit_profile_js_block.html

Closes #3958.
Removes JQTE from Edit Profile templates
Note: the clean theme already had no JQTE loader for textarea fields

Fix field display bug on Edit Profile page

---

src/repository/logic.py
src/repository/views.py
src/templates/admin/repository/manager.html

This PR closes #3657 
- This PR removes the summary from the dashboard page.
- A report has been added in its place: ttps://github.com/BirkbeckCTP/reporting/pull/37/

#3657 removed the repository metrics summary from the dashbaord page, now available in the reporting plugin

---

src/templates/admin/review/decision.html

- When an article is Unassigned, return to Unassigned
- All others should return to the decision helper page
- Closes #3987

#3987 when making an accept or decline review decision the "Cancel & go back" button now returns the editor to the correct pages

---

src/utils/logic.py

This feature is only supposed to fire when the target is an Article or Preprint, this PR makes sure that it only fires when one of those sets the request.site_type.
Closes #3992

Fixed an issue where bounced email notifications failed with an error due to not being linked to a journal or repository

---

src/press/templatetags/press_url.py

Quote is missing in class attribute in HTML markup generated by svg_or_image  templatetag

Fix missing quote in generated html

---

src/templates/admin/elements/breadcrumbs/unassigned_base.html
src/templates/admin/review/projected_issue.html
src/templates/admin/review/unassigned.html
src/templates/admin/review/unassigned_article.html

created an unassigned_base 
assigned across unassigned article and the unassigned article \ projected issue pages.
Closes #3797

Breadcrumbs added to unassigned templates

---

src/core/janeway_global_settings.py

This PR removes django countries which is causing fresh installs of Janeway on master to break.

Removed django countries from the master branch

---

src/repository/models.py

repository_download_file is manager only view whereas repository_file_download is public view. Updating the download url so that correct item url in OAI and JATS metadata for repository items.

PreprintFile download_url should point to the public url

---

src/themes/OLH/templates/elements/journal/article_filter_form.html
src/themes/clean/templates/journal/articles.html

all file search for labels which nested their input and only two were found, both in theme templates marked as depreciated in 1.5.1.
Labels elsewhere looked un-nested, and hence avoiding this issue.
Closes #3906

#3906 un-nest labels and inputs in themes

---

src/journal/views.py
src/production/logic.py
src/production/views.py

Stops multiple galley image files with the same name from being loaded in the edit galley interface.

---

src/core/logic.py
src/templates/admin/elements/forms/group_submission.html
src/templates/admin/elements/metadata.html
src/utils/install/journal_defaults.json

I believe this solution covers most of the request in #3738, as Phillipa is talking about the editors section of the article metadata page. However, in discussion with @mauromsl we noted that an editor may still reveal themselves when rejecting a paper as their email address will be used in the reply-to section.
There is some discussion to be had about how we approach this, do we want to enable the anonymous rejection of papers easily? The public display of an editorial board means that either way this is only partially anonymous as an author will be aware of who the editors are generally.
Personally I think this solution is enough, as editor should be accountable for article decisions, if editors _do_ want to circumvent the reply-to setup they could make use of a generic account to desk …

Adds a new setting to conceal the editor details when an author is viewing their article's metadata.

---

src/submission/models.py
src/templates/admin/elements/article_jump.html

As `workflow_stages` is used elsewhere I've opted to add a new method that explicitly returns distinct `WorkflowElements`. This will also reduce the number of queries run as the template will no longer be fetching related items.
Closes #3593

Fixes an issue where multiple jump links appear in an article's workflow nav when it has been moved through the workflow in a non linear fashion

---

src/templates/common/elements/edit_profile_js_block.html
src/themes/clean/templates/core/accounts/edit_profile.html

following #3983 , This PR adds support for the same feature on all three themes edit profile page.
Note: Clean theme was not making use of `edit_profile_js_block.html` and was instead using the same code in the `edit_profile.html` template, so this PR brings that theme inline with the others

Added support for clearing fromatting from pasted inputs onto the user page data

---

src/production/logic.py

closes BirkbeckCTP/pandoc_plugin#17
closes #3609
Fixes an issue originally reported on pandoc plugin where prettifying any loaded HTML galleys would lead to newline characters to be injected after every tag. As a result, when a formatting tag such as `<em>` or `<strong>` was followed by punctuation marks, an unwanted whitespace character was being rendered

Fixes additional whitespace being added after italics and bold to HTML galleys 

---

src/themes/clean/templates/journal/article.html

Spotted this on AUP who are using clean as their base theme. This now matches OLH and Material.
The clean theme will now correctly display the first frozen author's name in the article page's title.
Closes #4030

Correct display of author last names on Clean theme

---

src/core/janeway_global_settings.py

closes #4034 
closes #4035 
Configures our default TinyMCE editor to use the browser native API for full screen. Allows using Esc for closing full screen natively, regardless of keybinds on TinyMCE

Rich text editor now supports escape to close the full screen view

---

src/templates/admin/core/manager/users/index.html

problem was with forms not communicating correctly with each other.  Updated with code from @ajrbyers to fix this.  Tested the fix.
Closes #3785

#3785 bugfix - control user if statement contents updated

---

src/core/logic.py
src/templates/admin/elements/forms/group_article.html
src/themes/OLH/templates/journal/article.html
src/themes/clean/templates/journal/article.html
src/themes/material/templates/journal/article.html
src/utils/install/journal_defaults.json

- Closes #3088
- Unifies the display of date_submitted and date_accepted by introducing settings and adding them to all themes.
Note: OLH displays date published in the metrics/summary box.

#3088 Editors can now determine whether the date submitted and date accepted display for their articles on all themes

---

src/admin.py
src/apps.py
src/core/janeway_global_settings.py
src/core/models.py

- Closes #3202 
- This PR also includes definitions for a custom Janeway admin site, currently used just to overwrite the admin page title but can be extended in the future.

Django's admin interface will now use the email field for authentication

---

.gitignore
src/transform/xsl/default.xsl

Request to enhance the **verse-line** element template to support the **style** attribute. If the **style** attribute is present, then its value is passed to the resulting HTML via the inclusion of a **span** element. If the **style** attribute is not present, then behavior is not changed.
Currently, it appears the default behavior is inline and monospaced. This request allows for the ability to control the styling of the content within the verse-line element.
For example, the following JATS markup:
```
<disp-quote content-type="epig">
<verse-group>
<verse-line style="display:block;font-style:italic;font-family:serif">"Make no little plans. They have no power to stir men’s blood."</verse-line>
<verse-line style="display:block;font-style:italic;font-family:serif">Daniel Burnham, as quoted …
```

Add XSL support for the JATS verse-line/@style attribute

---

src/journal/urls.py

checked it was a duplicate. Checked functioning without it. Reviewed whole file for other duplicates and found none.
removed duplicate.
Closes #3775

Removed a duplicate URL (should not have any practical implications)

---

src/templates/admin/elements/review/draft_decisions_js.html
src/templates/admin/review/draft_decision.html
src/templates/admin/review/revision/request_revisions.html

Fixes #4088.
I checked all the places we include JQTE in forms, and made sure they did not interfere with a TinyMCE-powered field. These were the only two problems:
I checked and cleared these fields:
These fields are not actively used:

[1.5.2] Fix a bug that kept some rich-text fields from saving

---

.gitignore
src/transform/xsl/default.xsl

Request to add support for the JATS email element in all contexts.
Currently, the following JATS markup:
> `<p>Conny Liegl, Designer for Web, Graphics and UX, <email>cliegl@calpoly.edu</email></p>`
produces the following HTML display:
> ![image](https://github.com/BirkbeckCTP/janeway/assets/34096219/68f79654-81c0-4f54-9638-1d74e2a6cbf6)
This request will allow for the following HTML display and allow the generation of an email message to the address:
> ![image](https://github.com/BirkbeckCTP/janeway/assets/34096219/f7f69963-02cd-4917-877a-8af421976fe6)

Add XSL support for the JATS email element in all contexts

---

src/journal/forms.py
src/journal/logic.py
src/journal/views.py
src/templates/admin/elements/email_form.html
src/templates/admin/elements/publish/author.html

The same thing as #4094, but for 1.5.1 in case we want to include it in that release. Closes #4089.

[1.5.1] Fix form for notifying author of publication

---

src/core/forms/__init__.py
src/core/forms/forms.py
src/journal/logic.py
src/journal/views.py
src/templates/admin/elements/publish/author.html

This uses a bare-bones Django form to put TinyMCE into an arbitrary template as a hotfix for #4089. It does not fully address #4089 because we would like to refactor it a bit more in a later minor version of Janeway--see #4094.

Patch Notify Author email field with TinyMCE

---

.lando.yml
docker-compose.yml
dockerfiles/Dockerfile
requirements.txt
src/core/models.py
src/templates/admin/core/base.html
src/themes/OLH/templates/core/base.html

4072 django 4 2

---

src/review/forms.py

The share reviews form now uses the TinyMCE widget.
Closes #4086

Fixes a bug that stopped the Share Reviews page from loading properly.

---

requirements.txt

During a recent fresh installation I ran into an issue with pip install of psycopg2-binary. Version 2.8.6 uses an outdated installation method.
I am proposing bumping this to 2.9.8. I've read the changelog and don't believe there are any breaking changes for us between these versions, but please double-check. Version 2.9.9 drops support for python 3.6, so I don't think we should
go that far until we drop python 3.6.

Update psycopg2-binary version

---

src/core/migrations/0092_xslt_1-6-0.py
src/utils/migrations/0033_upgrade_1_6_0.py

Migration names does not include the extensions

Fix migration names

---

src/themes/OLH/templates/core/news/index.html
src/themes/clean/templates/core/news/index.html
src/themes/material/templates/core/news/index.html

identified templates as core/news/index.html across themes OLH, Material and Clean.
previously used striptag and truncatesmart
updated to truncatewords_html and safe
truncatesmart was set at 400 char, have used 50 words as an equivalent.
there are other templates which also use striptag and truncatesmart, these may need to considered for a similar update.
Closes #2123

#2123 news item template tag filters updated for HTML

---

src/templates/admin/core/dashboard.html

added an empty breadcrumb block to dashboard template to override the default behaviour (for when there is no breadcrumb block) thus removing the breadcrumb.
Closes #3821

#3821 Dashboard Breadcrumb removed

---

src/themes/OLH/templates/elements/journal/issue_block.html
src/themes/clean/templates/elements/journal/issue_block.html
src/themes/material/templates/elements/journal/issue_block.html

Closes #4150. 
This adds support for plural section names on the issue page. If there are two or more articles in a section for a given issue, the plural name will appear on all themes:
If there is only one article for the issue and section, or no value in the plural field for that section, it is singular:

Display plural section name on issue page

---

src/core/janeway_global_settings.py
src/transform/xsl/default.xsl

As noted on latest XML files from UCL:
- Fixed `lpage` in `element-citation` not being rendered
- Fixed figure labels being procesed twice due to explicit handle + apply-templates
- Titles in notes section have been moved out of `<ol>` so that they no longer are indented accidentally

XSLT: Fixed Page ranges on element-citation objects and figure labels being rendered twice

---

src/journal/logic.py

Table modal originally was a copy of table, so all ids were same as original ids.  Not all elements in table have id.
- prefix `copy-of-`
- added to table id
- added to all child ids of that table
paired programming with @mauromsl 
Closes #3909

#3909 table popups updated to have unique ids

---

Makefile
README.md
docs/source/installation.rst

It shouldn't affect most users, as `docker-compose` has not received updates since 2021 and docker itself ships with a symbolic link from `docker-compose` to `docker compose` in most distributions.
In any case, I've set the compose command as an environment variable so that systems stuck on the old python based docker-compose could still override it if needed.
closes #4190

Replaced use of deprecated `docker-compose` command in favour of `docker compose`

---

src/themes/OLH/assets/scss/app.scss
src/themes/OLH/templates/journal/article.html
src/themes/material/assets/mat.css
src/themes/material/templates/journal/article.html

The OLH and Material themes no longer use header tags to display metrics.

---

src/copyediting/views.py
src/templates/admin/copyediting/copyediting.html

- Added a new column that displays a list of copyeditors with links to the editor review page
- Moved the link to open an article's copyediting page from the "view" column (now deleted) to the title column
- Closes #4159

Adds a new column to the copyediting dashboard showing assigned copyeditors.

---

.github/ISSUE_TEMPLATE/a11y_report.md

new template for accessibility issue reporting.
using the a11y tag
based on bug report template
asks for missing alt-text not to be reported at present unless part of the alt text audit (to reduce likelihood of multiple reports - better to do this as one audit than accept these issue individually).
Closes #3836

#3836 create accessiblity issue reporting template

---

requirements.txt
src/core/janeway_global_settings.py
src/core/model_utils.py
src/core/tests/test_models.py
src/utils/const.py

This implements the discussed solution of borrowing from `bleach-allowlist` to cover the standard set of HTML elements and CSS properties that are safe to include in bleached fields.
Fixes #4195.

Update the HTML tags and CSS styles that are allowed in rich-text content

---

src/submission/forms.py

When addtional fields are set to the date type they now use the HTMLDateInput widget.
Closes #4102

#4102 additional fields with the date type now display the correct widget

---

src/core/forms/forms.py
src/core/model_utils.py
src/core/tests/test_models.py
src/core/views.py
src/identifiers/views.py
src/journal/views.py
src/themes/OLH/templates/elements/journal/article_list_filters.html
src/themes/clean/templates/elements/journal/article_list_filters.html
src/themes/material/templates/elements/journal/article_list_filters.html

These changes were made to provide functionality for BirkbeckCTP/consortial_billing#65.
They update the filterable class-based view in these ways:
- Make the methods essentially generic by checking to see if it is a set of articles before doing article-specific things
- Add filter types integer, search, and boolean
- Add a simple way to search using Django admin's search functionality

Updates to class-based view for filterable lists

---

src/templates/admin/journal/publish_article.html

- Adds two warnings, one when there is no set license and another when the set license has no URL.
Closes #2270

A warning will show in prepublication when an article has no license set.

---

src/copyediting/views.py
src/core/views.py
src/journal/views.py
src/proofing/views.py
src/review/views.py
src/submission/views.py

- Some older views that pre-date multitenancy were not filtering by the current `request.journal`.
- Added filters where gaps were identified.
- Closes #4256 
Note: Two other approaches were discussed and should be considered for future:
1. Switching these views to a new decorator that includes these checks
2. Switching these views to CBVs that inherit from a parent that has these checks

#4256 updates views with journal filters.

---

src/utils/transactional_emails.py

- When a review is completed both the editor and reviewer emails now are logged.
- Closes #4269

Adds logs to both emails sent when a review is completed.

---

src/templates/common/elements/password_rules.html
src/themes/OLH/templates/core/accounts/register.html
src/themes/clean/templates/core/accounts/register.html
src/themes/material/templates/core/accounts/register.html

Removed visible template tags from all theme registration pages

---

src/themes/clean/templates/elements/journal_footer.html

Fixes unclosed footer link in clean theme

---

src/templates/common/accounts/register_privacy_policy.html
src/themes/OLH/templates/core/accounts/register.html
src/themes/clean/templates/core/accounts/register.html
src/themes/material/templates/core/accounts/register.html

- The registration page now considers the press' privacy policy (following current convention this will also apply to repositories).
- Closes #4282

Registration page now uses the correct privacy policy link for presses

---

src/review/admin.py

While `ReviewAssignment.review_round` is usually set by logic functions, in case of customization of the workflow this might be `None`, it's best to check its value before accessing an attribute of the foreignkey

Check field value before accessing an attribute

---

src/journal/urls.py

- This reverts a change ot the funder_articles url pattern.
- Closes #4295

Reverts change to funder_articles url pattern.

---

src/themes/OLH/templates/journal/article.html
src/themes/material/templates/journal/article.html

- Share icons now have aria-labels on OLH and Material themes (no share icons found on Clean).
- Dyslexia, text size, print icons now have aria-labels on OLH (not found on Material or Clean).
- How to Cite icon now has Aria label and is no longer invisible to screen reader or keyboard navigation (tested with Mac Voice-over).  The dropdown inside it for different citation format also now works with tab and screen reader.
- The options hamburger button for narrow windows how has an aria label for 'options'.
All tested with Mac Voice Over.  Related bugs noticed (such as difference in order between visual and tab) which will feed into the current A11y audit, but as for what was reported in this issue, that has now been fixed.
Closes #3936

3936 add alt text to social media buttons

---

src/review/tests.py
src/submission/models.py
src/templates/admin/review/decision.html

Closes https://github.com/BirkbeckCTP/janeway/issues/4251
We found that open review counts for some reviewers were higher than expected because incomplete reviews from rejected articles were still open.
- Close incomplete review assignments when an article is rejected
- Add a callout to the "decline" email form that tells the user this will happen.

Close incomplete review assignments when an article is rejected

---

src/static/common/css/common.css
src/templates/common/elements/skip_to_main_content.html
src/themes/OLH/assets/js/app.js
src/themes/OLH/templates/core/base.html
src/themes/clean/templates/core/base.html
src/themes/material/templates/core/base.html

- Adds a new common template
- Replaces existing skip to content for clean
- Adds ID to `<main>`
- Closes #3932

Adds a skip to content link to all themes that is tab navigable

---

src/copyediting/models.py
src/core/models.py
src/core/templatetags/dates.py
src/core/templatetags/due_dates.py
src/core/templatetags/uuid.py
src/static/admin/js/check_all.js
src/templates/admin/core/widgets/select_all.html
src/templates/admin/core/widgets/soon_date_buttons.html
src/templates/admin/elements/datatables.html
src/templates/admin/elements/publish/pubdate.html

This adds a few template tags, widgets, and model properties that I used in fixing BirkbeckCTP/typesetting#166.
- A set of buttons that select or deselect all the checkbox inputs in a fieldset (an upgrade of of the jquery-based check_all.js, which could only be used once per page and was not accessible)
- A `detail` method on the galley object to make it possible to provide information about the linked file in a form choice
- A set of buttons that make it easier to quickly infill a date
- Support for initiating multiple datatables on a single page

Buttons and labels for complicated forms

---

src/templates/admin/review/home.html

Closes #4342 
Example article with only a revision request post change:

#4342 revision requests now show on the review dashboard even when no review assignments have been created

---

src/themes/OLH/assets/js/table_of_contents.js
src/themes/OLH/templates/journal/article.html
src/themes/clean/templates/journal/article.html
src/themes/material/assets/toc.js
src/themes/material/templates/journal/article.html

Updated django templates to check that there are galleys before creating download and checksum lists, across all three themes. Material already checked for galleys for download lists, but not for checksums.
For empty autogenerated tables of contents in OLH theme, updated the JS to remove the `toc` element if no headings were found, i.e. if list not populated.
Marked as draft as it is the end of the day, and I have yet to test this, so that must be done before sending for review.

3911 do not render empty lists on article page

---

src/themes/clean/templates/elements/journal/citation_modals.html

Clean now uses `frozenauthor_set` like OLH already does.
Closes #2422

Updates clean to use frozen authors for citation modals.

---

src/identifiers/logic.py

Swapped `logger.error` to `logger.info` as its expected that this may fail and is not actually an error.
Closes #2190

Updates logger output when extracting citations fails

---

src/journal/models.py
src/journal/urls.py
src/journal/views.py
src/submission/models.py
src/templates/admin/core/nav.html
src/templates/admin/journal/manage/published_article_archive.html
src/templates/admin/journal/manage/rejected_archived_article_archive.html
src/utils/db_functions.py

This PR:
- Closes #4362 
- Closes #3952
This PR introduces a custom Aggregate function, GroupConcat, to concatenate query results into a single string with support for PostgreSQL, MySQL/MariaDB, SQLite, and MSSQL
This PR splits the archive page into two views. One for published articles and one for archived articles.
Additionally the use of subqueries massively reduces the number of database round trips and speeds the page up exponentially for installs with large numbers of published or archived articles.

Splits back content archive into two views, removes query round trips to improve load time.

---

src/submission/models.py
src/templates/common/encoding/article_bibtex.bib
src/templates/common/encoding/article_ris.ris

Updates RIS and BIBTEX with additional information and 
- Closes #3771 
- Closes #3571

Fixed an issue with middle names and added support for page ranges in RIS and BIB exports (zotero, endnote, etc)

---

src/templates/admin/submission/start.html

This PR fixes the display of the copyright notice agreement label.
Before:
After:

Fixes the copyright notice label.

---

src/core/templatetags/orcid.py

Small tweak in order to continue supporting login through custom themes, it is important to preserve the default behaviour.
Registration behaviour also changes, however due to the use of a new shared template, the impact is less severe/non-existing

Resolves a backwards incompatible changed introduced in ORCID login template

---

src/submission/forms.py
src/submission/tests.py
src/submission/views.py
src/templates/admin/submission/submit_review.html

Closes #4421
- Removes `competing_interests` from ArticleInfo base class
- Adds new child class `EditArticleMetadata` which inherits from `ArticleInfo`
- `EditArticleMetadata` adds `competing_interests` as one of its fields

Fixes a bug where submit_info would clear CI.

---

src/press/migrations/0031_staffgroup_staffgroupmember.py

Ensure that column 'press_press.journal_footer_text' is created during the  clean install.

Fix issue #4027.

---

src/templates/admin/submission/edit/metadata.html

This is an emergency patch for v1.7 to fix a bug in the pii tag setup.
- Moves `can_see_pii` variable into the content block
- Updates if variable type

Fixes a bug that blocked editors from changing author metadata

---

src/themes/OLH/templates/journal/article.html
src/themes/clean/templates/journal/article.html
src/themes/material/templates/journal/article.html

- Adds a check to OLH template to ensure preprint is published
- Extends this feature to clean and material as it was not present there
Closes #3996 
**Note**: I'm aware that this PR contains bad use of header tags but they follow the current pattern and will be fixed as detailed in site structure issues.

Ensures that when an article and preprint are linked the preprint is only displayed if it is published.

---

src/journal/views.py
src/templates/common/elements/funder_info_for_readers.html
src/themes/OLH/templates/journal/article.html
src/themes/clean/templates/journal/article.html
src/themes/material/templates/journal/article.html

Fixes #4461.
See my comment on the original issue for a diagnosis: https://github.com/openlibhums/janeway/issues/4461#issuecomment-2437595887
To make the behavior clear and still display the various IDs for metadata purposes, I have laid out the data using a definition list. I have opted to use the `key_value_above` template from the back office as it is agnostic of styling. If crossing between the themes in this way is undesirable, I can move `key_value_above` to common templates.

Make display of funding info clearer on article page

---

requirements.txt

When doing a clean install pytz is missing.
```python
File "/var/www/vermont/src/cms/models.py", line 17, in <module>
from utils.logic import build_url_for_request
File "/var/www/vermont/src/utils/logic.py", line 12, in <module>
from core.middleware import GlobalRequestMiddleware
File "/var/www/vermont/src/core/middleware.py", line 9, in <module>
import pytz
ModuleNotFoundError: No module named 'pytz'
```
It may previously have been loaded automatically but another dependency but now adding it on its own.

Adds pytz as a dependency

---

src/security/test_security.py
src/templates/admin/review/revision/request_revisions.html
src/templates/admin/review/revision/request_revisions_notification.html
src/templates/admin/review/view_review.html

Removes missed PII from review and revision interfaces

---

src/journal/logic.py
src/submission/models.py
src/templates/admin/elements/publish/warnings.html
src/templates/admin/journal/publish_article.html
src/templates/admin/submission/edit/metadata.html

- If no corresp author is present adds this as a warning
- When no corresp author is found set `author_initial['to']` to None, form validation will handle it being empty
- The change above surfaced a bug with in `article.non_correspondence_authors` also fixed by this PR
- The notification template had additional protection as it checked whether the given article had peer reviews, this was not present in the logic file so posting this form would error due to the second form not being present. This check is now also present in the logic.
- Shifts prepub warnings into their own file and inseted with an include.
- Closes #4477

Fixes two issues related to prepublication author and reviewer notifications

---

src/submission/models.py

Fixes the display of date_submitted and date_accepted on OLH and Material themes

---

src/core/templatetags/escaping.py
src/themes/OLH/templates/core/news/index.html
src/themes/OLH/templates/core/news/item.html
src/themes/OLH/templates/journal/homepage_elements/news.html
src/themes/OLH/templates/press/core/news/index.html
src/themes/OLH/templates/press/core/news/item.html
src/themes/clean/templates/journal/homepage_elements/news.html
src/themes/material/templates/core/news/index.html
src/themes/material/templates/core/news/item.html
src/themes/material/templates/journal/homepage_elements/news.html
src/themes/material/templates/press/core/news/item.html

Fixed an issue where html tags where being displayed on news item titles

---

README.md

There is a typo in the hyperlink of "how we develop Janeway" in the main README. This PR fixes it.

Fix typo in README link from old BirkbeckCTP site

---

src/utils/transactional_emails.py

Refactored notification formatting for article decision recording and fixes a typo

---

.gitignore
src/transform/xsl/default.xsl

Currently, the following JATS markup
`<notes><title>Notes</title><fn-group><fn id="n1"><p>...</p></fn><fn id="n2"><p>...</p></fn>...</fn-group></notes>`
produces the following HTML output using the **fn-group/fn** template:
`<h2>Notes</h2><li xmlns:tei="http://www.tei-c.org/ns/1.0" id="n1">...</li><li xmlns:tei="http://www.tei-c.org/ns/1.0" id="n2"></li>...`
The markup above produces a HTML list with bulleted markers. 
This request should modify the HTML output using a new template **back/notes/fn-group** to be the following and allow the notes to appear as an ordered list:
`<h2>Notes</h2><ol class="footnotes"><li xmlns:tei="http://www.tei-c.org/ns/1.0" id="n1">...</li><li xmlns:tei="http://www.tei-c.org/ns/1.0" id="n2">...</li>...</ol>`

Xsl notes ordered list

---

src/core/forms/forms.py

NOTE: This needs to be merged into a release_1_7_x branch.
Contributes to openlibhums/consortial_billing#82.
Deployment note: It would be ideal to get this on OLH along with openlibhums/consortial_billing#87 before the release of Janeway 1.8. What's the best way to do that?

Make sure choices are sorted in search views

---

src/journal/urls.py

We do not link to this view anymore but is being hit  by bots and raising constant server errors/deprecation warnings.
I've kept the view as to preserve backwards compatibility but removed the URL entry
closes #4495

fix: disable URL for deprecated view #4495

---

src/core/forms/forms.py
src/core/views.py

The new article list views (Relying on GenericFacetedListView) rely on GET method to apply filtering. They use a django form to render facets and filters, however the form was not being validated, leading to server errors and potential SQL injection when malformed data was sent via query parameters. We now validate all query parameters ahead of executing any queries.
closes #4497

Fixed an issue where article list pages could throw an error for invalid filters

---

src/themes/OLH/assets/js/table_of_contents.js
src/themes/material/assets/toc.js

Fixes TOC generation to ensure it leaves the tags alone.
Also fixes irritating edge case where a tag has an empty .

Fix TOC generation to handle empty <a> tags and nested elements correctly

---

src/core/templatetags/files.py

Clicking on Document Management causes an error since the recent addition of annotated_files to the file_type template tag if the typesetting plugin is not installed.
Suggested fix.

fix annotated files if typesetting plugin is not installed

---

src/core/forms/forms.py
src/core/tests/test_views.py
src/core/views.py

Fixes #4532.
This branch fixes a regression that caused results on the Journal User page to leak across journals. It also fixes an additional more obscure bug where the count shown in the facet was inaccurate. It also adds a few regression tests to make sure this does not happen in the future. The tests related to pagination are an unrelated bonus.

Fix bug where search results leaked across journals

---

src/templates/admin/journal/contact.html
src/themes/OLH/templates/journal/contact.html
src/themes/OLH/templates/press/journal/contact.html
src/themes/clean/templates/journal/contact.html
src/themes/material/templates/journal/contact.html

closes #4268 
Note from @ajrbyers:
- Steph and I discussed the approach at length and did some reasearch around validation. We decided to disable HTML5 validation as recommended by the UK Gov Frontend team: https://design-system.service.gov.uk/patterns/validation/

contact forms validate on server not browser

---

src/submission/forms.py

Updated the `save` method in `EditFrozenAuthor` to set `frozen_email` to an empty string (`""`) instead of `None` after linking an existing account.
Closes #4572

Fixes an error when adding frozen authors with email that match existing accounts

---

src/templates/admin/elements/move_to_next_modal.html

- Adds text to explain the current stage and the stage the article will move to.
Closes #3965

#3965 adds text to the move_to_next modal.

---

src/themes/OLH/templates/core/base.html
src/themes/clean/templates/core/base.html
src/themes/material/templates/core/base.html

Updated `base.html` for the three themes.
before:
after:
Closes #4228

a11y #4228 prevent non-telephone numbers becoming call links

---

src/identifiers/logic.py
src/identifiers/tests/test_logic.py
src/journal/models.py
src/templates/common/identifiers/crossref_article.xml
src/templates/common/identifiers/crossref_conference.xml

This completes 3 of 5 requests in #3131:
- map Janeway's first page and last page fields to Crossref
- output clean proceedings title
- respect custom publisher names set at journal level
Depending on if the reporter is happy with these fixes alone, closes #3131.

Crossref deposit improvements

---

src/security/decorators.py

Not particularly important, but I thought I'd report :slightly_smiling_face: 
In the decorator `article_stage_accepted_or_later_or_staff_required`, there is an `if` clause that might try to access an attribute of a None object.
To replicate, one should log-in to a journal and manually enter the URL of a non existing article in order to trigger the view "article_file_download" (`views.serve_article_file`).
E.g. https://olh.openlibhums.org/article/id/20000/file/1234/  (ATM article 20000 does not exist).
HTH

Don't look for an attribute on None object

---

src/core/logic.py
src/journal/models.py
src/submission/models.py
src/utils/install/journal_defaults.json

Add a setting to make the automatic registrations of DOIs at acceptance be optional, while still allowing the manual registration.
Rationale: ATM that the same setting `use_crossref` is used
- for automatic registration at acceptance [`Article.accept_article()`](https://github.com/openlibhums/janeway/blob/dcc8f7c25e1e66b8cfda89d18add2a08aa1412ee/src/submission/models.py#L1516) 
- for manual registration after publication [`identifiers.views.issue_doi()`](https://github.com/openlibhums/janeway/blob/dcc8f7c25e1e66b8cfda89d18add2a08aa1412ee/src/identifiers/views.py#L272)
so that it's not possible to disable automatic registration at acceptance while retaining the possibility of manual registration at publication (for instance).

Let automatic registration of DOIs be optional.

---

src/comms/views.py

- Added a try/except block that returns a 404 instead of a 500 when attempting to fetch an image for a `NewsItem` that does not exist.
- Closes #4438

When attempting to fetch an image for a NewsItem that does not exist a 404 not found error is now returned

---

src/core/forms/forms.py

Fixes #4607.
Note that this is hot-fixed on OLH as well, so that the Supporters Manager country field works.
The bug does not directly affect most Janeway users because only the Supporters plugin uses this field, to my knowledge.

Fix bug that kept filter from working on some search views

---

src/static/common/js/clipboard.js
src/themes/OLH/templates/elements/journal/share.html
src/themes/OLH/templates/journal/article.html
src/themes/clean/templates/elements/journal/share.html
src/themes/clean/templates/journal/article.html
src/themes/material/assets/mat.css
src/themes/material/templates/elements/journal/share.html
src/themes/material/templates/journal/article.html

- Drops all share links on all themes
- Adds a field with either the DOI or canonical URL
- Adds copy to clipboard common JS script
- Closes #4390

Removes share links from the article page and replaces them with a share link and copy button

---

src/core/views.py
src/review/logic.py
src/review/models.py
src/review/views.py
src/templates/admin/core/manager/users/history.html
src/templates/admin/elements/review/add_reviewer_table_row.html
src/templates/admin/review/add_review_assignment.html

This PR adds a new completed reviews manager and tidies up the display of review information when assigning reviewers or looking a their histories.
Example:
Previously this user would have shown multiple active reviews and the review that was withdrawn would be the latest completed date/time.
Closes #4392

Ensures that active reviews count is accurate

---

src/repository/forms.py

When a user starts the process for a new repository submission, the box is always pre-ticked. The current code checks if the form model is False, but it is actually an instance of `<class 'repository.models.Preprint'>`. This updates the logic to check if the instance has an id, which it won't if not yest saved to the database, but it will have an id if it has been saved.
Fixes #4636

Fix #4636 - pre-ticked repo submit agreement

---

src/templates/admin/elements/core/addressee_display.html

The addressee display template was updated to include a check for PII, but the implementation assumes that the item being managed is an article in a journal, but that template fragment is also used by the repository log.
Adds some logic to check if the article variable is defined before applying PII checks. This means that PII checks are not appliedd to repository email addresses in this list, but as none of the rest of the PII functionality is built out for repository side, this seems reasonble.
Fixes #4637

Fixes issue with repository log view

---

src/themes/OLH/assets/scss/app.scss
src/themes/clean/assets/css/clean.css
src/themes/clean/templates/journal/article.html
src/themes/material/assets/mat.css
src/themes/material/templates/journal/article.html
src/transform/xsl/default.xsl

a11y #4244 keywords markup as lists

---

src/templates/common/elements/journal/article_title.html
src/themes/OLH/templates/journal/article.html
src/themes/OLH/templates/journal/print.html
src/themes/clean/templates/journal/article.html
src/themes/clean/templates/journal/print.html
src/themes/material/templates/journal/article.html

- Adds a new common template for rendering article page titles (for use on article.html and print.html)
- Removes corresp authors surname from title
- Fixes print template struct
- Closes #4679

Removes correspondence author's name from the article page

---

src/themes/clean/templates/journal/collections.html

Fixes a bug that caused clean theme collections to be in a single column

---

src/core/templatetags/dates.py
src/core/tests/test_templatetags.py

- This  closes #4666 however there are browser issues that we cannot fix (such as Chrome's built-in datetime-local widget providing its own Now button that uses the browsers timezone.

Updates the offset_date tag to take the users preferred timezone into account

---

src/templates/admin/repository/submit/files.html

fix: When upload is limited to PDF, the text now displays HTML properly

---

src/journal/migrations/0053_display_article_images_settings.py

Originally I tried to fix this migration but realised that there no circumstances under which it will ever work in the future or be useful. The migration was added over two years ago so it has no effect for new installs and anyone still using a version of Janeway that old is very unlikely. The _es setting value will always be missing and it will be skipped or it will error out. We need to decide, for the future, how to handle adding new languages in a safe way or ensure that all migrations will always run. It may be that we need to shift the altering of settings like this _out_ of the migration process all together (although it has proven convenient up until now).
This closes #4632 
Once merged we can create a 1.7.5 release.

Removes data migration that causes errors during setup

---

src/journal/migrations/0053_display_article_images_settings.py

Fixes #4632 for the 1.7.x release.
This has already been implemented on master:
```
b24495c1b fix: remove data migration that will never fire (#4632)
486cc2c88 fix: fixes an issue that caused migrations to fail (#4632)
```

Fix a bug that caused migrations to snag

---

src/templates/admin/review/thanks.html

This is a bleachfield so should be output as safe on templates.

Review form thanks message is now marked safe and no longer displays HTML tags

---

src/core/views.py
src/templates/admin/core/manager/users/history.html

This adds both publication and submission history of a user to the history section. A link to the archive page of the article is also provided if the article isn't in the "UNSUBMITTED" stage. 
Preview:

Add Submissions and Publications to User History

---

src/templates/admin/review/in_review.html

Adds a template hook to the in_review.html page, inside the editor's action menu block.
This allows plugins to inject additional action items during the review stage,
enabling better extensibility.
This hook is added to support the development of the RQC Adapter Plugin (https://reviewqualitycollector.org/) for Janeway, which needs to inject additional editor actions during the review stage.

feat: add hook for editor actions menu on in_review page

---

src/typesetting/templates/typesetting/elements/file_list.html

file_list.html currently checks for the editor role but it is not defined in the template meaning it will never display for editors.

The options block will now show for editors in Typesetting, allowing them to do conversions

---

src/core/apps.py
src/core/upgrade.py
src/janeway/__init__.py
src/utils/migrations/0011_upgrade_1_3_5.py
src/utils/migrations/0013_upgrade_1_3_6.py
src/utils/migrations/0014_upgrade_1_3_7.py
src/utils/migrations/0015_upgrade_1_3_8.py
src/utils/migrations/0019_upgrade_1_3_9.py
src/utils/migrations/0020_upgrade_1_3_10.py
src/utils/migrations/0023_upgrade_1_4_0.py
src/utils/migrations/0025_upgrade_1_4_1.py
src/utils/migrations/0026_upgrade_1_4_2.py
src/utils/migrations/0027_upgrade_1_4_3.py
src/utils/migrations/0028_upgrade_1_4_4.py
src/utils/migrations/0030_upgrade_1_5_0.py
src/utils/migrations/0031_upgrade_1_5_1.py
src/utils/migrations/0032_upgrade_1_5_2.py
src/utils/migrations/0033_upgrade_1_6_0.py
src/utils/migrations/0035_upgrade_1_7_0.py
src/utils/migrations/0037_upgrade_1_7_1.py
src/utils/migrations/0038_upgrade_1_7_2.py
src/utils/migrations/0039_upgrade_1_7_4.py
src/utils/models.py

Removes the need for adding migration bumps manually.
Closes #4826

Auto-record Janeway version bumps using signals

---

requirements.txt

Closes #4859.
I have read the changelog and do not believe there are any breaking changes.
The new pinned version (3.10.1) still supports Python 3.9+.

Upgrade django-simple-history

---

src/core/templatetags/fqdn.py
src/core/tests/test_templatetags.py

Our `stateless_site_url` is not stateless because django's `reverse` checks the `script_prefix` set for the context of the request. I've changed this to invoke the resolver directly with a script prefix override and allow the site-implemented `site_url` to control if a prefix should be inserted to the URL or not.

Fixed a bug where rendering URL from journal A to journal B would lead to both journal codes being appended

---

src/templates/admin/elements/icons/page_next.html
src/templates/admin/elements/icons/page_previous.html
src/templates/admin/reports/metrics.html
src/templates/common/elements/pagination.html
src/themes/OLH/templates/core/news/index.html
src/themes/OLH/templates/elements/journal/issue_paginator.html
src/themes/OLH/templates/journal/articles.html
src/themes/OLH/templates/press/core/news/index.html
src/themes/OLH/templates/repository/list.html
src/themes/clean/templates/core/news/index.html
src/themes/clean/templates/elements/journal/issue_paginator.html
src/themes/clean/templates/elements/pagination.html
src/themes/clean/templates/journal/articles.html
src/themes/clean/templates/press/core/news/index.html
src/themes/material/templates/core/news/index.html
src/themes/material/templates/elements/journal/issue_paginator.html
src/themes/material/templates/journal/articles.html
src/themes/material/templates/preprints/list.html
src/themes/material/templates/press/core/news/index.html
src/themes/material/templates/repository/list.html

pagination arrows a11y update

---

requirements.txt
src/templates/common/apis/OAI_ListSets.xml

Addresses a couple of problems when upgrading uiowa to v1.8.x:
- Adds a OAI fix that exists already in their live instance but not on core
- Updates requirements to be compatible with python 3.12 (Ubuntu LTS 24.04 default python version)

Fixes for Uiowa upgrade

---

src/copyediting/views.py

Fixes #4939.
The extra comma is from 056b29151b86ec3ece82d2ea4a3bbe47100bad52. Ruff formatting made the tuple look intentional but it was just a typo.

Fix a server error that happened when deleting an author copyediting review
