openlibhums/janeway

src/comms/urls.py, src/comms/views.py, src/themes/OLH/templates/press/core/news/index.html, src/themes/OLH/templates/press/core/news/item.html
A pr to pull patches from 1.0.1 into master.
=> 1.0.1 Patches

src/review/models.py, src/review/views.py
and check that the assignment.form is the element.form.
=> When saving a review form we now pass the assignment

src/utils/management/commands/backup.py
Backup command now uses call_command to export JSON rather than subprocess.
Reported in: https://github.com/BirkbeckCTP/janeway/issues/546
=> Updated backup command #546

src/templates/admin/core/article.html, src/templates/admin/journal/manage/archive_article.html
Adding the admin hooks for the archive plugin. I also added hooks in our custom theme - can PR those for OLH theme if you like.
=> Add Admin Hooks for Archiving Plugin

Dockerfile, Makefile, README.md, docker-compose.yml, requirements.txt, src/core/example_settings.py, src/utils/management/commands/install_janeway.py
Adds support for mysql and postgres (alongside postgres) when running docker-compose commands.
Also fixes #592
=> Add support for different RDBMS from docker-compose

src/journal/views.py, src/templates/admin/elements/issue/table_of_contents.html
Adds a header for ToC, Add Article link and fixes Section FK for ArticleOrdering on this page.
Closes #607
=> Fix for #607

src/core/example_settings.py
Closes #598 
I've also updated the settings repo
=> #598: Add default umask for file uploads

src/utils/management/commands/install_janeway.py
Forgot this cherry-pick for mysql
=> Closes #592

src/themes/OLH/templates/core/nav.html, src/themes/OLH/templates/journal/collections.html, src/themes/OLH/templates/journal/issue_display.html, src/themes/default/templates/core/nav.html, src/themes/default/templates/journal/collections.html, src/themes/default/templates/journal/issue_display.html, src/themes/material/templates/core/nav.html, src/themes/material/templates/journal/collections.html, src/themes/material/templates/journal/issue_display.html, src/utils/install/journal_defaults.json
=> Feature #622 Adds new setting for renaming 'Collections'

src/press/models.py
Fixes "Selected Articles" Carousel mode not working.
=> Closes #631

src/themes/OLH/templates/journal/submissions.html, src/themes/default/templates/journal/submissions.html, src/themes/material/templates/journal/submissions.html
=> #660: Don't render a section if there isn't a setting for it in submissions.html

src/themes/material/templates/journal/article.html
=> 662: Fixes rendering article content as None on material theme

src/themes/material/templates/journal/homepage_elements/carousel.html
=> 668: Removes carousel parent div

src/templates/admin/production/index.html, src/templates/admin/proofing/index.html
=> Closes #652

src/core/example_settings.py, src/utils/notify_plugins/notify_email.py
=> #665: Stop sending email notifications to users with dummy email adress

src/core/logic.py, src/themes/OLH/templates/journal/submissions.html, src/themes/default/templates/journal/submissions.html, src/themes/material/templates/journal/submissions.html, src/utils/install/journal_defaults.json
=> 680 submission intro text

.dockerignore
=> #684: Adds db volumes to .dockeringore

src/core/views.py, src/templates/admin/press/press_manager_index.html
=> Adds Clear Cache button to press manager

src/themes/OLH/templates/journal/collections.html, src/themes/material/templates/journal/collections.html
=> collection pages should call collection.issue_title

src/submission/urls.py, src/submission/views.py, src/templates/admin/submission/manager/delete_license.html, src/templates/admin/submission/manager/licenses.html
=> Added a new staff only confirmation page for deleting licenses.

src/submission/migrations/0029_auto_20181128_1651.py, src/submission/tests.py
- Tweaked the migration to make it reversible
- Added a test for signals
- Closes #700
=> Added test and tweaked migration.

src/core/admin.py, src/core/models.py
- Returns an error where the article_id is missing but doesn't break the page
- article_pk is now a read-only field in admin to stop this happening in future
- Closes #653
=> Added handler for odd edge case. Made field read only to avoid in future

src/core/include_urls.py
=> 654 UUID regex

src/production/forms.py, src/production/logic.py, src/production/views.py, src/templates/admin/production/assign_typesetter.html
Added a new form with validators and dropped custom form validator from logic.py.
Closes #635
=> Closes #635

src/themes/OLH/assets/js/table_of_contents.js, src/themes/OLH/templates/journal/article.html, src/themes/default/templates/journal/article.html, src/themes/material/assets/mat.css, src/themes/material/assets/toc.js, src/themes/material/templates/journal/article.html
=> Sidebars now loop over all header tags in the article.

src/submission/views.py, src/templates/admin/submission/submit_authors.html
This function is too long, need to move to forms/logic but a fix is in place for the empty search issue.
https://github.com/BirkbeckCTP/janeway/issues/721
=> Added handler for empty author searches.

src/static/admin/css/admin.css, src/submission/models.py
=> Closes #719 and Closes #615

src/core/homepage_elements/featured/plugin_settings.py, src/submission/models.py, src/submission/views.py, src/templates/admin/elements/metadata.html
=> 723 bugfix author records

Makefile, docker-compose.yml
=> #758: Removes no longer needed docker CMD overrides

src/core/logic.py
=> #764: Adds missing argument to load_plugin_apps call

Makefile
=> Change logic for backup suffixes

src/core/middleware.py
ImproperlyConfigured wasn't imported into the Middleware.
=> Added missing import

.dockerignore, Makefile, docker-compose.yml, dockerfiles/Dockerfile, dockerfiles/Dockerfile.base, requirements.txt, src/core/janeway_global_settings.py, src/security/decorators.py
=> 788 Janeway base docker image

src/security/decorators.py, src/security/test_security.py
=> #793: Improves logging on deny_access

src/copyediting/forms.py, src/core/views.py, src/templates/admin/copyediting/upload_file.html, src/templates/admin/core/dashboard.html, src/templates/admin/elements/publish/pubdate.html, src/templates/admin/proofing/do_proofing.html
Trello card: https://trello.com/c/W7ju84Xk/494-795-132-bugs#
Issue: #795
=> 795 bugfixes

src/templates/admin/journal/sitemap.xml, src/themes/OLH/templates/elements/journal/social_meta.html, src/themes/default/templates/elements/journal/social_meta.html
=> Fix Article URLs with double Base URL (1.3.2 Compatible)

requirements.txt, src/core/janeway_global_settings.py
=> Switch to simple_math as the default captcha setting

docker-compose.yml, src/core/dev_settings.py, src/core/janeway_global_settings.py, src/utils/__init__.py, src/utils/tests.py
=> Adds Dev settings and functionality to merge settings from 2 sources

src/themes/OLH/templates/core/base.html, src/themes/OLH/templates/press/core/base.html, src/themes/material/templates/core/nav.html
=> #741: Hide cms page edit if no page in context

src/templates/admin/copyediting/add_copyeditor_assignment.html, src/templates/admin/copyediting/author_review.html, src/templates/admin/elements/metadata.html, src/templates/admin/journal/document_management.html, src/templates/admin/preprints/article.html, src/templates/admin/production/assign_typesetter.html, src/templates/admin/production/assigned_article.html, src/templates/admin/production/edit_galley.html, src/templates/admin/production/edit_typesetter_assignment.html, src/templates/admin/production/typeset_task.html, src/templates/admin/proofing/proofing_article.html, src/templates/admin/proofing/request_typesetting_changes.html, src/templates/admin/review/add_files.html, src/templates/admin/review/revision/do_revision.html, src/templates/admin/review/revision/view_revision.html, src/templates/admin/review/unassigned_article.html
Adding the upload date to the galley and file management tables.
=> Date uploaded in files tables

src/templates/admin/core/article.html
=> #774: Fixes template variable typo

src/core/migrations/0025_fix_bad_journal_urls_in_template.py
=> #835: Adds migration to fix all bad urls in settings

src/templates/admin/core/manager/settings/index_home.html
Have fun reviewing this one :smile:
=> Closes #726

src/production/urls.py, src/production/views.py, src/templates/admin/production/assigned_article.html, src/templates/admin/proofing/preview/embedded.html, src/templates/admin/proofing/preview/epub.html, src/templates/admin/proofing/preview/rendered.html
=> Closes #781. Added a preview galley button.

src/submission/models.py, src/templates/admin/elements/core/kanban/card.html, src/templates/admin/elements/production/card.html
=> Closes #854

src/core/dev_settings.py, src/production/models.py, src/production/views.py, src/templates/admin/production/assigned_article.html, src/templates/admin/production/edit_typesetter_assignment.html
=> Closes #812, makes managing typeset tasks fit description given.

src/core/migrations/0025_fix_bad_journal_urls_in_template.py
Completes PR #840 
closes #866
=> 835 migrate bad template urls

src/templates/admin/press/edit_press.html
=> #769: Adds jqte to edit press form

src/core/forms.py, src/core/janeway_global_settings.py, src/core/views.py, src/static/common/css/common.css, src/templates/common/elements/static-error-messages.html, src/themes/OLH/templates/core/base.html, src/themes/OLH/templates/core/login.html, src/themes/default/templates/core/base.html, src/themes/default/templates/core/login.html, src/themes/default/templates/core/nav.html, src/themes/material/templates/core/base.html, src/themes/material/templates/core/login.html
=> 693 login form improvements

src/core/files.py, src/core/models.py, src/templates/admin/production/assigned_article.html, src/templates/admin/production/edit_galley.html, src/templates/admin/proofing/proofing_article.html
=> Added missing images features to HTML galleys

requirements.txt
1.11.19 didn't last for long...
=> Bumps Django to 1.11.20

src/production/views.py, src/review/logic.py
=> Fixes a couple  of bad URLs sent on emails

src/templates/admin/production/edit_galley.html
=> When the galley images table is empty display a message.

src/core/logic.py, src/journal/logic.py, src/journal/views.py
=> #864: ammends bad path from refactor

src/journal/views.py
=> #905: Allows downloading collections

src/copyediting/forms.py, src/copyediting/views.py, src/templates/admin/copyediting/add_copyeditor_assignment.html
=> 731 copyediting assignment form

src/journal/models.py
=> Closes #912: fixes default article section missing.

src/production/urls.py, src/production/views.py
Closes #919 
@mdlincoln this is the PR for image previewing in production.
=> #919 adds a view for previewing article galley images in production

src/copyediting/forms.py, src/copyediting/views.py
=> #938 Fixed a bug where copyedit files were not being saved.

src/security/logic.py
=> #934 fixes multiple objects returned for correction tasks

src/journal/models.py
=> #600 wasn't a bug but I pep8'd some of the signals

src/cms/models.py
=> #948: Adds back NavigationItem.url

src/themes/material/templates/journal/article.html
=> #952 fixes tag over two lines

src/core/dev_settings.py
=> #845: Removes duplicate EMAIL_BACKEND entry in dev_settings

src/events/logic.py, src/events/registration.py, src/review/logic.py, src/review/views.py, src/templates/admin/review/unassign_editor.html, src/utils/install/journal_defaults.json, src/utils/transactional_emails.py
=> 855: Adds email page to editor unassign view

src/security/decorators.py, src/security/test_security.py
=> Allow authors to access their proofreading tasks

src/identifiers/models.py, src/journal/urls.py, src/journal/views.py
=> Added URLs to specifically handle DOIs.

src/core/dev_settings.py, src/core/migrations/0028_fix_bad_email_urls.py, src/utils/install/journal_defaults.json
=> Fixes bad urls on email settings

src/cms/views.py, src/templates/admin/cms/nav.html, src/templates/admin/elements/cms_nav.html
Tried to be consistent with the current interface, we really need to revamp this page
Closes #986
=> Adds support for deleting custom nav items

src/templates/admin/elements/article_jump.html
=> #806 adds a new link to the article jump drop down

src/copyediting/models.py
=> #763, changed log string slightly for decison

src/templates/admin/production/assigned_article.html
Closes #595, second issue reported here has been fixed previously as part of #635.
=> #595, tweaked the status guideance for production stage.

src/themes/OLH/templates/core/accounts/activate_account.html, src/themes/OLH/templates/core/accounts/orcid_registration.html, src/themes/OLH/templates/preprints/article.html, src/themes/material/templates/core/accounts/activate_account.html, src/themes/material/templates/core/accounts/register.html, src/themes/material/templates/core/accounts/reset_password.html, src/themes/material/templates/core/nav.html, src/themes/material/templates/preprints/article.html
=> #1006, moves trans tags onto one line

src/core/templatetags/truncate.py
=> #1014 fixes None value bug for truncatesmart

src/core/models.py
=> #1018 Fixes downloads with no authors/correspondence author

src/templates/admin/review/suggest_reviewers.html
Closes #760 
Made the choice simply to add a button to allow them to decline as we don't want to annoy reviewers.
=> #760 Adds button to decline to suggest reviewers

src/journal/models.py, src/review/views.py
=> #1029: Fixes URL logic for author review emails

src/themes/OLH/templates/journal/homepage_elements/html_block.html
=> #996 added html block to OLH theme with styling.

src/review/forms.py, src/review/urls.py, src/review/views.py, src/templates/admin/review/review_form.html
=> 751 review form fixes

src/core/context_processors.py
=> add order_by sequence to navigation filter

src/themes/OLH/templates/journal/article.html, src/themes/default/templates/journal/article.html
=> #1036 added author lists when article images are disabled

src/utils/install/journal_defaults.json
=> Changes setting name in defaults and adds a subject for it.

src/production/urls.py, src/production/views.py, src/templates/admin/journal/manage/archive_article.html, src/templates/admin/production/assigned_article.html, src/templates/admin/production/non_workflow_assign.html
updated view to assign user as PM.
Closes #1001
=> #1001 added link to production, updated production template

src/press/templatetags/press_url.py, src/themes/OLH/templates/core/base.html, src/themes/OLH/templates/press/core/base.html
=> Updates OLH base templates.

src/journal/models.py
=> #1068 issues now check for date published and stage.

src/proofing/logic.py, src/proofing/models.py, src/proofing/views.py, src/templates/admin/proofing/edit_proofing_assignment.html, src/templates/admin/proofing/proofing_article.html
Closes #673.
Decision made to change this to allow for a reset button.
=> Proofing assignments can now be reset to their original state.

src/submission/admin.py, src/submission/models.py
=> #1077 fixes admin implementation

src/utils/setting_handler.py
=> Deprecates 'create' keyword argument in get_setting

src/core/middleware.py
=> 1089: Removes noisy log line from middleware

src/identifiers/logic.py, src/themes/default/templates/identifiers/crossref.xml
=> Adds article license to crossref metadata export

src/journal/views.py, src/templates/admin/journal/document_management.html
place return url as hidden input in upload form. change redirect to have the return var as GET.
pr for https://github.com/BirkbeckCTP/janeway/issues/980
=> add return url to file upload in document management

src/core/homepage_elements/html/hooks.py, src/core/homepage_elements/html/plugin_settings.py, src/core/homepage_elements/html/views.py, src/core/tests/test_settings.py, src/core/views.py, src/utils/setting_handler.py
Helps with #1111
Reported issue still not resolved.
=> Improve installation of HTML homepage element/plugin

src/core/views.py
=> 1105 Editors can now access template pages.

src/core/models.py, src/static/admin/js/modal.js, src/templates/admin/copyediting/article_copyediting.html, src/templates/admin/elements/notes/note_script.html, src/templates/admin/journal/publish_article.html, src/templates/admin/production/assigned_article.html, src/templates/admin/proofing/proofing_article.html, src/templates/admin/review/in_review.html
=> #1108 fixes note submission for path mode.

src/templates/admin/core/manager/email/edit_email_template.html, src/templates/admin/core/manager/settings/edit_setting.html, src/templates/admin/elements/core/default_setting_card.html
=> 1104 EMail template page now displays the default setting.

src/core/templatetags/pages.py, src/themes/OLH/templates/journal/articles.html, src/themes/material/templates/journal/articles.html
=> 1128: Slices page jump links

src/review/views.py, src/templates/admin/review/manager/preview_form.html, src/templates/admin/review/notify_reviewer.html
=> Moves review form preview to the correct view

src/core/workflow.py, src/production/views.py
=> Task complete redirects to dashboard on 302

src/utils/importers/shared.py
=> Use html parser for imported html galleys

src/journal/models.py
=> #1197: Articles sort by sequence when no SectionOrdering available

src/core/templatetags/render_string.py, src/templates/admin/copyediting/article_copyediting.html, src/templates/admin/production/assigned_article.html, src/templates/admin/proofing/proofing_article.html, src/templates/admin/review/in_review.html, src/utils/install/journal_defaults.json
=> Adds a "Steps" guide to all stages and allows customizing them via settings

src/utils/management/commands/install_journal.py
install_journal in its current form doesn't copy over the licences to then 2nd, 3rd ... journal installed
remedy this
=> also install licenses when issuing install_journal

src/themes/default/templates/identifiers/crossref.xml
=> Adds AccessIndicators namespace declaration to Crossref template

.gitignore, src/core/views.py, src/proofing/logic.py, src/proofing/urls.py, src/proofing/views.py, src/templates/admin/core/dashboard.html, src/templates/admin/elements/proofing/proofreader_correction_card.html, src/templates/admin/proofing/correction_requests.html
=> Added a new proofing corrections listing page.

src/themes/default/templates/identifiers/crossref.xml
Corrected the order of the `journal_article` elements
=> Fix crossref license

src/core/views.py
=> Added some @has_journal checks to links presses may see.

src/utils/importer.py, src/utils/importers/shared.py, src/utils/importers/up.py, src/utils/management/commands/scrape_up_page.py
- Adds support for issue title
- Adds support for issue description
- Fixes images missing extension
=> Up importer fixes

src/core/logic.py, src/core/views.py, src/submission/forms.py, src/templates/admin/submission/edit/metadata.html, src/templates/admin/submission/submit_info.html, src/utils/install/journal_defaults.json
Includes tweaks to boolean defaults to make them match correct True and False strings.
Closes #1213
=> Added a new setting to make abstracts required.

src/core/homepage_elements/about/forms.py, src/core/homepage_elements/about/hooks.py, src/core/homepage_elements/about/plugin_settings.py, src/core/homepage_elements/about/templates/about_settings.html, src/core/homepage_elements/about/views.py, src/core/homepage_elements/news/plugin_settings.py, src/themes/material/templates/journal/homepage_elements/about.html, src/utils/setting_handler.py
=> #959 Makes title of about block configurable.

src/events/logic.py, src/events/registration.py, src/proofing/logic.py, src/proofing/models.py, src/proofing/urls.py, src/proofing/views.py, src/templates/admin/proofing/delete_proofing_round.html, src/templates/admin/proofing/proofing_article.html, src/utils/install/journal_defaults.json, src/utils/transactional_emails.py
=> 1200 delete proofing round

src/templates/admin/journal/publish_article.html
=> 1183 updated text.

src/review/views.py, src/templates/admin/elements/review/card.html, src/templates/admin/elements/review/review_request_metadata.html, src/templates/admin/review/review_requests.html
=> 1190 review metadata

src/journal/views.py, src/preprint/logic.py, src/production/logic.py, src/production/views.py
=> 1164 other galley delete

src/themes/material/templates/journal/homepage_elements/carousel.html, src/themes/material/templates/journal/homepage_elements/carousel_element.html
=> 926 when the carousel only has 1 item, repeat that item.

src/core/views.py, src/journal/forms.py, src/journal/logic.py, src/journal/urls.py, src/journal/views.py, src/static/admin/js/popup.js, src/templates/admin/copyediting/article_copyediting.html, src/templates/admin/core/email_user.html, src/templates/admin/core/manager/users/history.html, src/templates/admin/core/manager/users/index.html, src/templates/admin/elements/journal/log_description.html, src/templates/admin/elements/metadata.html, src/templates/admin/journal/send_user_email.html, src/templates/admin/production/assigned_article.html, src/templates/admin/proofing/proofing_article.html, src/templates/admin/review/in_review.html
=> 1184 editor contact user

src/themes/OLH/templates/elements/journal/issue_top.html, src/themes/OLH/templates/journal/articles.html, src/themes/OLH/templates/journal/authors.html, src/themes/OLH/templates/journal/become_reviewer.html, src/themes/OLH/templates/journal/collections.html, src/themes/OLH/templates/journal/editorial_team.html, src/themes/OLH/templates/journal/issues.html, src/themes/OLH/templates/journal/search.html, src/themes/OLH/templates/journal/submissions.html, src/themes/default/templates/core/base.html, src/themes/default/templates/journal/article.html, src/themes/default/templates/journal/editorial_team.html, src/themes/default/templates/journal/submissions.html, src/themes/material/assets/mat.css, src/themes/material/templates/elements/accounts/edit_profile_body_block.html, src/themes/material/templates/journal/editorial_team.html
=> 1229 updated theme headers.

src/copyediting/views.py, src/journal/views.py, src/production/views.py, src/proofing/views.py, src/review/views.py, src/security/decorators.py, src/security/templatetags/securitytags.py, src/security/test_security.py, src/submission/models.py, src/templates/admin/elements/article_jump.html, src/templates/admin/elements/production/card.html, src/templates/admin/production/index.html, src/templates/admin/review/unassigned_article.html
Will close #1165 . Tests to be added.
=> 1162 given SE access to the workflow pages.

requirements.txt
=> Bump django version.

src/proofing/logic.py
=> #1180: Allows editors to be chosen as proofreaders

src/templates/admin/journal/publish_article.html
Also moved Issue above DOI in list.
Closes #997
=> #997 diplays disabled button when no date_published set.

src/templates/admin/review/delete_review_round.html
=> Added a missing question mark.

src/core/views.py
=> #1097 isnull for date_declined is now marked as True.

src/templates/admin/core/dashboard.html, src/templates/admin/elements/production/card.html
=> #1100 added route from dashboard for production manager.

src/templates/admin/review/view_review.html
=> #975 added some logic to hide sections.

src/journal/views.py, src/templates/admin/journal/replace_file.html
=> #985 handle missing files.

src/core/views.py
=> #1243 added integrity error catch incase an account already exists.

src/proofing/forms.py, src/proofing/views.py, src/templates/admin/proofing/request_typesetting_changes.html
Also tidies up the view a little.
Closes #1127
=> #1127 when creating a correction task we now display a checkbox.

src/core/logic.py
Fixes the JPG bug of not being able to save alpha channels
=> Fix bug with saving JPGs with alpha channel

src/utils/setting_handler.py
=> Fix UnboundLocalError on plugin settings handler

src/metrics/logic.py
=> #1262 fixes bug by fetching object.

src/core/homepage_elements/issue/plugin_settings.py
=> #1266: Current Issue homepage element was loading wrong context

src/core/homepage_elements/featured/plugin_settings.py
=> #1269 fixes bug

src/utils/install.py
=> #1272 changes short_name to code

src/themes/OLH/assets/scss/app.scss
=> #1287: break line on words that overflow article block

src/journal/migrations/0032_add_issue_type.py, src/journal/migrations/0033_migrate_issue_types.py
=> Split schema from  data migration on journal 0033/0032

src/submission/migrations/0025_auto_20180508_1138.py
=> Fix misspellings under Competing Interests

src/security/logic.py
=> Grants typesetters access to replace files during proofing

src/core/logic.py
=> #1298: Fixes a couple of wrong calls to overwrite_file

src/journal/logic.py, src/journal/management/commands/merge_issues.py, src/journal/management/commands/merge_sections.py
Provides a couple of merge commands for merging issues and sections
=> Merge commands

src/review/views.py
Changes the permissions from staff only to " at least senior editors"
=> Allows editors to manage review forms

src/themes/OLH/templates/elements/journal/citation_modals.html
=> #1286: Display issue/volume numbers in citations only if present

src/templates/admin/proofing/proofing_article.html
=> #1319: Adds preview link to article proofing page

src/submission/models.py
=> Changed wording and fixed typo

src/security/decorators.py
=> #1331: Adds base check to a couple of decorators

src/templates/admin/proofing/typesetting/typesetting_corrections.html
=> Adds metadata modal to proofing corrections page

src/production/logic.py, src/production/tests.py, src/production/views.py
Closes #473 
@ajrbyers I've also removed inline css, although it wasn't explicitly mentioned on the original issue. Does that sound sensible?
=> Removes all CSS from uploaded HTML Galleys.

src/journal/models.py, src/journal/views.py
- Issues won't render rejected articles
- Issue manager won't let you add rejected articles to an issue
=> Issue to ignore rejected articles

src/themes/OLH/templates/journal/article.html, src/themes/default/templates/elements/article_meta_tags.html, src/themes/default/templates/journal/article.html, src/themes/material/templates/journal/article.html
=> Fixes article meta tags to accomodate for google scholar recommendations

src/journal/models.py, src/themes/OLH/templates/elements/journal/issue_sidebar.html, src/themes/OLH/templates/journal/collections.html, src/themes/default/templates/elements/journal/issue_sidebar.html, src/themes/default/templates/journal/collections.html, src/themes/material/templates/elements/journal/issue_sidebar.html, src/themes/material/templates/journal/collections.html
=> Rewordings on the collections page to accomodate for custom collection types

src/templates/admin/journal/document_management.html, src/templates/admin/production/assign_typesetter.html, src/templates/admin/production/assigned_article.html, src/templates/admin/production/edit_galley.html, src/templates/admin/production/edit_typesetter_assignment.html, src/templates/admin/production/typeset_task.html, src/templates/admin/proofing/proofing_article.html, src/templates/admin/proofing/request_typesetting_changes.html, src/templates/admin/review/unassigned_article.html
=> Swapped date_uploaded for date_modified on files from Copyediting onward

src/templates/admin/copyediting/add_copyeditor_assignment.html, src/templates/admin/elements/datatables.html
=> Closes #1323 and fixes a datatables template bug."

src/templates/admin/elements/metadata.html
=> Wraps email popup in an IF. 

src/themes/OLH/templates/elements/journal/box_article.html, src/themes/default/templates/elements/article_listing.html, src/themes/material/templates/elements/article_listing.html
=> Links to all issues/collections an article belongs to from the article listing

src/themes/material/templates/core/nav.html
=> Fixes multiline trans tags

src/utils/install/journal_defaults.json
=> #1362: Untangles new 1.3.7 journal settings - closes #1362

src/utils/migrations/0014_upgrade_1_3_7.py
=> Adds v1.3.7 upgrade migration

src/submission/forms.py
=> Copyright notice logic now only executes if the field is enabled.

src/templates/admin/production/edit_galley.html
=> Remove edit images block when editing PDF galleys

src/templates/admin/production/assigned_article.html
=> Adds missing ID column to rows in production view

src/themes/OLH/templates/elements/journal/article_issue_list.html, src/themes/OLH/templates/journal/article.html, src/themes/default/templates/elements/journal/article_issue_list.html, src/themes/default/templates/journal/article.html, src/themes/material/templates/journal/article.html
Adds a new sidebar block displaying issues an article is a part of and linking to them.
Closes #1359
=> 1359 back to issue

src/core/logic.py, src/journal/models.py, src/journal/urls.py, src/journal/views.py, src/security/decorators.py, src/security/test_security.py, src/themes/OLH/templates/journal/keyword.html, src/themes/OLH/templates/journal/keywords.html, src/themes/default/templates/elements/journal/keywords_block.html, src/themes/default/templates/journal/keyword.html, src/themes/default/templates/journal/keywords.html, src/themes/material/templates/journal/keyword.html, src/themes/material/templates/journal/keywords.html, src/utils/install/journal_defaults.json
=> 767 keyword view

src/themes/OLH/templates/journal/homepage_elements/carousel.html, src/themes/default/templates/journal/homepage_elements/carousel.html, src/themes/material/templates/journal/homepage_elements/carousel_element.html
Called striptags to remove tags from the string before displaying.
Closes #1356
=> Updated carousels to striptags before truncating.

src/templates/admin/submission/edit/metadata.html
=> Re-arranges the metadata template to use two forms not one

src/templates/admin/copyediting/article_copyediting.html, src/templates/admin/copyediting/editor_review.html, src/templates/admin/journal/document_management.html, src/templates/admin/production/assigned_article.html, src/templates/admin/proofing/proofing_article.html, src/templates/admin/review/in_review.html
=> Added various edit in admin links to workflow pages.

src/templates/admin/review/home.html
=> 1417 Adds commas to split editors.

src/core/files.py, src/review/views.py, src/templates/admin/review/review_form.html
=> Added new option to hide file names in reviewer downloads.

src/templates/admin/submission/start.html
=> Added breakline to ensure that checkbox and label are on the same line

src/identifiers/logic.py, src/templates/common/identifiers/crossref.xml
=> Fixes Crossref deposits for publications without an ISSN

src/submission/migrations/0036_article_source_files.py, src/submission/migrations/0037_auto_20190808_1326.py
=> Fix unsupported migration on SQLite3

src/identifiers/urls.py, src/identifiers/views.py, src/templates/admin/identifiers/article_identifiers.html
This PR adds a feature to "show the generated XML DOI" which is useful for testing
=> Add functionality to show DOI XML

src/utils/importers/shared.py, src/utils/importers/up.py
Issue 51-52 volume 0 becomes:
```
{
"issue": 0,
"issue_title": "Issue: 51-52",
"volume": 0,
}
```
=> Add support for non numeric issue numbers on UP

src/journal/views.py
=> Clear cache on article publication.

requirements.txt, src/identifiers/logic.py
=> Rewrite DOI handler. 

src/themes/OLH/templates/journal/article.html, src/themes/default/templates/journal/article.html, src/themes/material/templates/journal/article.html
=> Add rel tag to all license templates.

src/core/janeway_global_settings.py
=> #1457: Sets default collation for MYSQL on settings.py

src/templates/admin/copyediting/editor_review.html
=> Adds author covering letter to editor copyedit review page

src/themes/OLH/templates/preprints/submit_start.html
=> #1468: Fix bad reference to base template

src/core/models.py, src/journal/models.py
@ajrbyers I haven't tested it with the preprints system but this should do the trick
v1.3.7 compatible
=> XSL allocation to handle articles with no journal

src/review/views.py, src/templates/admin/review/view_review.html
If there are no reviews, a permission denied error with a note.
=> Editors can now edit reviews before making them available to authors.

src/core/views.py, src/themes/OLH/templates/core/accounts/public_profile.html, src/themes/default/templates/core/accounts/public_profile.html, src/themes/material/templates/core/accounts/public_profile.html
- Fixes template for OLH and Default
- Adds template for Material :man_facepalming: 
- Fixes roles query to limit to current user
=> Closes #1446

src/templates/admin/journal/article_log.html
=> Log entries are not sorted by date with latest first.

src/utils/notify_plugins/notify_email.py
Closes #1462 
- When a user's email is in to: set the from address to be the journal.
=> Stop emails to the user from being sent from the user.

src/journal/views.py
=> Articles view checks for stage and pub date now.

src/templates/admin/core/nav.html
=> #1428 Added nav element for plugins to editor section.

src/core/files.py, src/core/migrations/0032_install_xsl_files.py, src/journal/logic.py, src/metrics/management/commands/accesses_to_historic.py, src/metrics/management/commands/process_crossref_events.py, src/metrics/management/commands/reload_access_dump.py, src/press/models.py, src/production/logic.py, src/themes/OLH/build_assets.py, src/transform/logic.py, src/utils/importers/up.py, src/utils/management/commands/backup.py, src/utils/management/commands/similarity_check_csv.py, src/utils/management/commands/update_defaults_json.py, src/utils/models.py, src/utils/upgrade/shared.py
=> Adds explicit encoding to most of  builtin open() calls

src/templates/admin/core/dashboard.html
=> #1475 author boxes are now full width.

src/core/models.py, src/journal/views.py, src/preprint/logic.py, src/production/logic.py, src/production/views.py, src/templates/admin/elements/production/new_galley.html, src/templates/admin/production/typeset_task.html
- Galley upload now has only one upload field
- Galley upload also has a label field
- We attempt to work out the best label if none is supplied
closes #1452
=> Updates Galley Upload

src/templates/common/identifiers/crossref.xml
closes #1533 
I also added the issue title which was missing
=> Fix cross ref issue pub date

src/journal/views.py
=> 935 updates store_article_access calls.

src/themes/OLH/templates/journal/article.html, src/themes/default/templates/journal/article.html
=> 1528 author affiliations olh theme

src/templates/admin/copyediting/do_copyedit.html
=> 1523 Make the copyediting information section useful

src/journal/logic.py, src/journal/views.py
Required for plugins to use their own permission logic
=> Moves some logic to logic module

src/themes/OLH/templates/journal/article.html, src/themes/default/templates/journal/article.html
=> #1563 default and OLH themes now use FAs for their title tag.

src/metrics/logic.py
=> Adds a lock around metrics logic

src/themes/OLH/assets/scss/app.scss, src/themes/default/assets/css/bootstrap.css, src/themes/material/assets/mat.css, src/transform/xsl/default.xsl
=> #1550 Added css changes for small caps.

src/themes/OLH/assets/js/table_of_contents.js, src/themes/OLH/assets/scss/app.scss, src/themes/material/assets/mat.css, src/themes/material/assets/toc.js
Closes #1364 and this is the last PR for 1.3.8 :fireworks:
=> #1364 Updated toc gen & styling to help make it... less of a mess.

src/submission/decorators.py, src/submission/views.py, src/themes/OLH/templates/elements/right_hand_menu.html, src/themes/OLH/templates/journal/submissions.html, src/themes/default/templates/403.html, src/themes/default/templates/journal/submissions.html, src/themes/material/templates/journal/submissions.html
=> 1521 disable submission

src/themes/OLH/templates/journal/homepage_elements/popular.html, src/themes/default/templates/journal/homepage_elements/popular.html, src/themes/material/templates/journal/homepage_elements/popular.html
=> 1526 the most popular template now uses the correct title

src/themes/material/assets/mat.css
=> #1535 Added list styling for article body.

src/core/homepage_elements/journals/hooks.py, src/core/homepage_elements/journals_and_html/hooks.py
=> #1522 featured journals are now sorted into alpha order.

src/journal/views.py
=> 1544 adds catch to issue assignment. PEP8 stuff too.

src/core/files.py, src/journal/views.py, src/review/views.py, src/themes/OLH/templates/journal/issues.html, src/themes/default/templates/journal/issues.html, src/themes/material/templates/journal/issues.html
Closes #1579 
Also includes a couple of tweaks or issue zip download.
=> #1579 Tweaks how we fetch issue articles for some instances.

src/submission/models.py, src/templates/admin/journal/publish_article.html
- If an article has completed reviews we now mark it as reviewed automatically
- Add warnings to the prepub page including one for peer review
Closes #1525
=> 1525 accepted article peer reviewed

src/review/views.py, src/templates/admin/review/review_form.html
I thought of keeping the two forms but have the second form submit the first as well.
Havign a single form  seems simpler and more intuitive to me
=> Merges review file form and review form

src/themes/OLH/templates/journal/submissions.html, src/themes/default/templates/journal/submissions.html
It was missing from both the default and OLH themes
=> Adds missing acceptance criteria block

src/review/views.py
=> #1613: Author can now download review files

src/review/views.py, src/templates/admin/review/revision/upload_file.html
=> Fix server error when posting a file upload without a file

src/templates/admin/elements/review/review_request_metadata.html
=> Render editor details properly

src/static/admin/css/timeline.css, src/templates/admin/submission/timeline.html
=> Fixes timeline not showing the funding block on /submit/start

src/themes/OLH/assets/scss/app.scss
It seems I forgot to throw a PR for this one
=> Fix info-bar covering issue cover

src/cms/views.py
=> Fix press trying to load journal nav items

src/core/views.py, src/core/workflow.py, src/templates/admin/core/kanban.html
=> Fixes logged exceptions on kanban view

src/metrics/logic.py, src/utils/decorators.py
This PR closes #1644 and resolves an incompatibility with MariaDB
Behaviour of this module will be fixed in #175
=> #1644: Retry concurrent read/writes on Article Access

src/journal/views.py
closes #1648
- Now iterates the received article ids instead of `issue.structure()`
- Catches bad input by verifying article belongs to requested issue and section.
=> Validate articles when setting ArticleOrdering

src/core/homepage_elements/carousel/templates/carousel_setup.html, src/core/include_urls.py
- Exposes translation JS as a URL
- Adds it to template
=> Fixed the carousel M2M widgets.

src/core/views.py
=> Editors can now access the plugins page

src/core/plugin_loader.py, src/core/views.py, src/core/workflow.py, src/submission/models.py, src/templates/admin/core/active_submissions.html, src/templates/admin/core/dashboard.html, src/templates/admin/elements/no_stage.html
- Adds a map of stages to workflow elements for core and plugin elements.
- Hardcoded link added for published articles
- When an article has no stage and thus we cannot ascertain what stage the article would be in an error is displayed.
=> #1654 changes how we handle lookups of elements and handles edge cases.

src/proofing/views.py
=> Fix proofing XML preview not rendering article

src/submission/models.py
=> Fix no workflow element for stage rejected

src/api/serializers.py, src/api/views.py, src/templates/common/apis/OAI.xml
The OAI feed wasn't filtering by journal which I assume its wrong
=> Fixes some errors on the REST API and OAI

src/core/logic.py
- Adds a try/except block to `get_available_elements`
- Logs output of try/except
- Closes #1667
=> #1667 Updated core logic to handle error.

src/core/homepage_elements/carousel/forms.py
=> #1678 Fixes bug by always setting querysets.

src/utils/importers/shared.py, src/utils/importers/up.py
- Case insensitive emails: Depends on the collation used in the source
database
- Alpha characters on issue numbers
- Wrong/missing contentypes on article galleys
=> Handle more discrepancies with OJS/UP on the importer

src/core/workflow.py
=> #1686: workflow element for typesetting is 'production' not 'typesetting

src/themes/OLH/templates/elements/journal/issue_top.html, src/themes/default/templates/elements/journal/issue_top.html, src/themes/material/templates/elements/journal/issue_top.html
=> #1673 issue editors are now displayed on the issue page.

src/journal/views.py
=> Checks article is published properly in article view

src/core/workflow.py
Closes https://github.com/BirkbeckCTP/typesetting/issues/90
=> Changed workflow complete message.

src/static/common/css/repo.css, src/themes/material/templates/repository/home.html
- Revise the submit button text on the repository home page to avoid
using a potentially wrong indefinite article
- fixes #1738
=> Revise object-related text for repository pages.

src/templates/admin/elements/publisher_notes.html, src/themes/OLH/templates/journal/article.html, src/themes/default/templates/journal/article.html, src/themes/material/templates/journal/article.html
- Publisher notes can now handle HTML.
=> Marks publisher notes as safe.

src/repository/views.py, src/static/common/css/repo.css, src/themes/material/templates/repository/list.html
=> #1767 added paginator to base of page.

src/repository/urls.py, src/repository/views.py, src/themes/material/templates/preprints/list.html, src/themes/material/templates/repository/home.html, src/themes/material/templates/repository/list.html
Kudos to @hardyoyo for getting this started.
=> 1633 search feature

src/repository/forms.py, src/repository/models.py, src/repository/urls.py, src/repository/views.py, src/security/decorators.py, src/templates/admin/press/nav.html, src/templates/admin/repository/fields.html, src/templates/admin/repository/manager.html
=> #1684 updated fields interface.

src/themes/material/templates/repository/base.html
needed for google analytics tracking
=> Preprints: add repository.custom_js to every page

src/core/include_urls.py, src/press/views.py, src/repository/models.py, src/repository/views.py, src/templates/admin/journal/sitemap.xml
seems to work on my test instance
=> [Preprints]: sitemap refactored like press.index

src/themes/OLH/build_assets.py, src/themes/OLH/templates/core/base.html
=> OLH build_assets  command to consider press overrides

src/repository/models.py, src/repository/urls.py, src/repository/views.py, src/templates/admin/repository/article.html, src/templates/admin/repository/author_article.html, src/templates/admin/repository/author_supp_files.html, src/templates/admin/repository/manage_supp_files.html, src/templates/admin/repository/supp_files_body.html, src/templates/admin/repository/supp_files_js.html
=> 1590 supp file manager

src/themes/material/templates/repository/preprint.html
=> #1825 fixed typo.

src/themes/material/templates/repository/preprint.html
=> [preprint] make the "Additional Metadata" header conditional

src/core/models.py, src/repository/logic.py, src/security/decorators.py, src/security/templatetags/securitytags.py, src/templates/admin/press/nav.html
=> Repository manager fix

src/cron/views.py
=> #1828 editors can now access the reminder manager

src/themes/OLH/templates/journal/article.html
- Fixed Facebook link
- Removed Google Plus as the service no longer exists
Closes #1795
=> #1795 fixed fbook link and remvoed G+ link.

src/themes/OLH/templates/journal/editorial_team.html, src/themes/default/templates/journal/editorial_team.html, src/themes/material/templates/journal/editorial_team.html
=> Sorts editorial team profile links

src/templates/admin/production/assign_typesetter.html
=> Prompt production manager that article has no projected issue

src/core/logic.py, src/review/forms.py, src/review/views.py, src/templates/admin/review/review_form.html, src/utils/install/journal_defaults.json
=> Allow Reviewers to save their review progress

src/themes/OLH/templates/core/news/index.html, src/themes/material/templates/core/news/index.html
=> #1879: Handle absence of default_carousel_image

src/identifiers/logic.py
=> Crossref deposit: Converts DOI URL into identifier format

src/core/models.py, src/themes/OLH/templates/core/accounts/public_profile.html, src/themes/default/templates/core/accounts/public_profile.html, src/themes/material/templates/core/accounts/public_profile.html
- Filters articles shown on public profile to just published articles
- In the context of a journal, filters the publications by the current journal
=> Show only published articles on public profile

src/themes/material/templates/repository/nav.html
the "Subjects" link should show up on mobile too
=> [preprints] add subject link to nav-mobile

src/templates/admin/review/add_files.html
=> Remove redundant download link

src/themes/default/templates/elements/journal/editorial_social_content.html
=> Fix typos on orcid logo

src/security/decorators.py
=> #1908: Add base check to security decorator

src/themes/material/templates/repository/preprint.html
- Adds a version number to the top of the page
- Hides Older Versions if there aren't more than one version
=> Makes preprint versions better on preprint page.

src/review/models.py
The `ReviewAssignment` reviewer field can't be `blank` but can be `null`, so we need to handle methods calling attributes on `self.reviewer`
Closes #1918
=> Handle __str__ when review has no reviewer

src/cms/models.py, src/cms/views.py, src/templates/admin/elements/cms_nav.html
closes #1917 
Also added some nice-to-have styling tweaks to the Navigation builder
=> Fix MultipleObjectsReturned on CMS nav builder

src/security/logic.py, src/templates/admin/journal/file_history.html
=> Handle Section Editor role on file permissions logic

src/journal/views.py
=> Handle current_issue when no issue is set

src/core/files.py
=> Fix return value on errors with XSLT

src/core/model_utils.py, src/core/tests/test_models.py
=> Fix model merger to handle custom through models used in M2M

src/press/views.py
fixes https://github.com/BirkbeckCTP/janeway/issues/1971
=> indent to fix issue 1971

src/themes/default/templates/elements/article_listing.html, src/themes/material/templates/elements/article_listing.html
=> #1987 updates article listing for material and default inline with OLH.

src/themes/material/templates/core/news/index.html
=> #1985 sorts the logic for fetching news images.

src/journal/views.py
=> #1993 adds defaults to issue-article ordering get_or_create

src/submission/models.py, src/themes/OLH/templates/journal/article.html, src/themes/material/assets/mat.css, src/themes/material/templates/journal/article.html
- Adds links to the material theme
- Bonus: shares the DOI url rather than journal URL when one is present
=> #1989: Adds social share links to article page

src/core/logic.py, src/themes/OLH/templates/journal/article.html, src/themes/material/templates/journal/article.html, src/utils/install/journal_defaults.json
Requested in support ticket 145.
=> Adds a new suppress_citations_metric setting.

Makefile, README.md, docker-compose.yml
Try and avoid having users ruin their install by running `make` before `make install`
=> Better makefile

src/templates/admin/review/home.html
=> Display status for all articles with review assignments

src/templates/admin/core/dashboard.html, src/themes/material/templates/core/news/index.html, src/themes/material/templates/core/news/item.html, src/themes/material/templates/journal/collections.html
=> 1.3.9 last fixes

src/core/logic.py, src/templates/common/elements/altmetric_badges.html, src/themes/OLH/templates/journal/article.html, src/themes/default/templates/journal/article.html, src/themes/material/templates/journal/article.html, src/utils/install/journal_defaults.json
Closes #2048
AND CLOSES 1.3.9 AM I RIGHT?
=> #2048 added support for altmetric badges.

src/core/forms.py, src/core/tests/test_models.py
=> Fix QuickUserForm overriding Account clean

src/core/workflow.py
=> Workflow plugins kanban articles now filtered by journal

src/core/model_utils.py, src/submission/models.py, src/submission/tests.py
- Adds the M2M interface to our custom M2M manager
- Adds a signal to preserve article keyword order when using that interface
=> Fix keywords m2m interface

src/journal/models.py, src/submission/forms.py, src/submission/tests.py, src/submission/views.py
=> Display all forms and licenses on edit metadata

src/journal/views.py
=> #2081 update order and section when a create doesnt occur.

src/submission/models.py, src/utils/forms.py
=> #2095: Fix broken method KeywordArticle.__str__

src/journal/views.py
=> #2113 only show published issues/collections in sidebar.

src/review/forms.py, src/review/models.py
=> #2107 fixes bug where review form elements couldn't have the same name

src/templates/admin/elements/review/review_meta_block.html, src/templates/admin/elements/review/review_request_metadata.html, src/templates/admin/review/review_form.html
=> #2101 the review page now includes metadata for the paper.

src/review/forms.py, src/templates/admin/review/add_review_assignment.html, src/templates/admin/review/edit_review.html
We talked about this one a while ago, might be worth including it in 1.3.10
=> Remove review_type option from review form

src/templates/admin/elements/issue/guest_editors.html, src/templates/admin/journal/manage/add_guest_editor.html, src/templates/admin/journal/manage/issues.html
=> Issue Page updates

src/review/models.py, src/submission/models.py, src/templates/admin/elements/review/review_block.html, src/templates/admin/review/home.html, src/templates/admin/review/in_review.html, src/templates/admin/review/revision/view_revision.html, src/utils/shared.py
=> #2122 updates the review home page.

src/core/forms.py
=> Include salutation in QuickUserForm

src/review/logic.py
=> #2168: Fix cardinality error due to group by assignment

src/review/views.py, src/templates/admin/review/decision_helper.html
=> Adds warnings and a toggle button for review visibility

src/identifiers/logic.py, src/templates/common/identifiers/crossref_article.xml, src/templates/common/identifiers/crossref_conference.xml
closes #2157 
Adds the following metadata:
- Article abstracts
- Author ORCID
- Author Affiliation
- Article acceptance date
Handles corporate authors correctly
=> Crossref export updates

src/journal/urls.py
This is a requirement for our friends at mpub, who use dot characters in their pubids. Would be good to have in 1.3.10
=> Allow dot character in pubids

src/core/include_urls.py, src/core/logic.py, src/core/templatetags/roles.py, src/core/views.py, src/journal/models.py, src/templates/admin/core/manager/index.html, src/templates/admin/core/manager/roles/role.html, src/templates/admin/core/manager/roles/roles.html, src/templates/admin/core/manager/users/enrol_users.html, src/templates/admin/core/manager/users/index.html, src/templates/admin/elements/core/user_search_list.html, src/templates/common/elements/hijack-notification.html
=> 2149 enhancement

src/utils/transactional_emails.py
=> Pass email rather than Account to notify

src/journal/migrations/0035_journal_xsl.py
Should fix the error that comes up when installing a 1.3.10 instance
=> Fix migration tree for journal 0035

src/utils/migrations/0020_upgrade_1_3_10.py
=> Bump Version 1.3.10

src/templates/admin/copyediting/notify_copyeditor_assignment.html, src/templates/admin/review/assignment_notification.html, src/templates/admin/review/notify_reviewer.html, src/templates/admin/review/revision/request_revisions_notification.html, src/templates/admin/review/unassign_editor.html, src/templates/admin/review/withdraw_review.html, src/utils/install/journal_defaults.json, src/utils/transactional_emails.py
=> Fix hard coded email subjects 

docs/source/changelog.rst, src/core/middleware.py, src/core/tests/test_middleware.py, src/journal/logic.py, src/templates/admin/elements/publish/pubdate.html
=> Fix timezone awareness when setting article publication date

src/core/views.py, src/utils/orcid.py
=> #2223 fixes login redirect issue

src/templates/admin/review/in_review.html
=> Adds back 'new review round' button to in review page

src/review/forms.py
The form field should not be allowed blank since it is required
closes #2212
=> Fix review assign with defaults not posting

src/themes/OLH/templates/journal/article.html, src/themes/material/templates/journal/article.html
=> #2243: Adds DOI to article page when available

src/themes/OLH/templates/elements/journal/citation_modals.html
close #2249
Also handle name suffixes introduced in v1.3.10
=> Fix use of frozen author in citation generator

src/themes/material/assets/mat.css, src/themes/material/templates/cms/page.html
=> Support browser default styling on <li> for CMS pages

src/transform/xsl/default.xsl
=> #2259: Fix doubling of URI elements

src/static/admin/css/app.css, src/templates/admin/core/base.html, src/templates/admin/elements/article_jump.html
=> Updates the article stages and logs button to a better display

src/journal/views.py, src/templates/admin/journal/document_management.html
=> #2194 document management now has data/fig upload and a label field

src/templates/admin/review/add_review_assignment.html
=> #2377 fixed template logic and some typos/text.

src/themes/OLH/templates/core/base.html, src/themes/clean/templates/core/base.html, src/themes/material/templates/core/base.html
- Adds new hook
- Fixes random clean block
- Rearranges blocks to be similar
Closes #2385
=> #2385 added new hook and re-arrannged some blocks

src/themes/OLH/templates/journal/article.html, src/themes/OLH/templates/journal/issue.html, src/themes/clean/templates/journal/article.html, src/themes/clean/templates/journal/issue.html, src/themes/material/templates/journal/article.html, src/themes/material/templates/journal/issue.html
Bonus - updates the issue page title to include the journal name
=> Adds ORCiD links in article page

src/static/common/css/common.css, src/themes/OLH/templates/core/accounts/register.html, src/themes/clean/templates/core/accounts/register.html, src/themes/material/templates/core/accounts/register.html
=> #2390 update the register page text

src/journal/urls.py, src/journal/views.py
Seems I hadn't committed the change to journal/urls.py in #2392
=> Custom identifier url

.update.sh, src/core/homepage_elements/about/plugin_settings.py, src/core/homepage_elements/html/plugin_settings.py, src/core/migrations/0047_hvad_to_modeltranslations.py, src/themes/OLH/templates/journal/article.html, src/utils/management/commands/install_janeway.py
Adds some fixes for v1.4 upgrades.
=> Add default settings for HTML and About.

src/core/forms.py, src/themes/OLH/templates/journal/editorial_team.html, src/themes/clean/templates/journal/editorial_team.html, src/themes/material/templates/journal/editorial_team.html
=> #2303: Editorial team description is now rich-text

src/submission/models.py
=> #2401 updates is_accepted

src/cms/forms.py, src/cms/views.py, src/templates/admin/cms/nav.html, src/templates/admin/elements/article_jump.html
=> #2413 stop cms tln from shoving themselves up their own arses.

src/themes/material/templates/elements/journal/issue_top.html
=> #2129: Add backdrop to issue title on material theme

src/review/forms.py, src/templates/admin/review/edit_review.html
=> #2426: Avoid assignment form set null after being edited

src/cms/views.py, src/templates/admin/cms/nav.html
=> Fix new/update nav item forms posted when toggling elements

src/repository/models.py, src/themes/material/templates/repository/elements/preprint_home_listing.html
=> #2090 completes this and closes #2090

src/journal/views.py, src/transform/xsl/default.xsl
=> Embeds a Vimeo player via XSLT

src/templates/admin/repository/article.html
=> Add preprint_doi to repository/article template

src/identifiers/logic.py, src/identifiers/models.py, src/templates/admin/journal/article_log.html
=> #2473 catches connection and timeout errors when connecting to crossref.

src/static/common/css/common.css, src/transform/xsl/default.xsl
=> #2469 added support for strike and monospace

src/themes/OLH/templates/journal/article.html, src/themes/material/templates/journal/article.html
=> #2480 fix date display when dates are missing.

src/api/permissions.py, src/api/urls.py, src/templates/admin/core/manager/users/enrol_users.html
- Adds a check for is_staff
- URLs are now reversed in `enrol_users.html`
- Text updated
- Closes #2488
=> #2487 hotfix for role assignment permission issue.

src/repository/migrations/0022_auto_20210303_1450.py
preprint author last name field should go to account last name field
=> author->acct last name update

src/transform/xsl/default.xsl
=> #2562 added a div around app H2s

src/templates/admin/repository/manager.html
=> [preprints] use `first.full_name` rather than `all.0.author.full_name`

src/submission/models.py, src/templates/common/apis/OAI_record.xml
=> OAI_record now displays full names.

src/submission/views.py
I've tracked this down to a merge conflict badly resolved between 5565c9e67 and f58e15469
closes #2546
=> #2546: Reinstates lost change from 5565c9e67

src/core/janeway_global_settings.py, src/journal/middleware.py, src/journal/urls.py, src/journal/views.py, src/templates/admin/core/nav.html, src/templates/admin/elements/forms/group_journal.html, src/templates/admin/elements/translations/form_tabs.html, src/templates/admin/journal/manage/languages.html, src/themes/OLH/templates/core/base.html, src/themes/OLH/templates/elements/journal_footer.html, src/themes/clean/templates/elements/journal_footer.html, src/themes/material/templates/elements/journal_footer.html, src/utils/install/journal_defaults.json
=> 2601 enhancement

src/copyediting/migrations/0008_fix_copyeditor_notify_author.py, src/core/logic.py, src/journal/logic.py, src/journal/views.py, src/static/OLH/css/app.css, src/static/clean/css/clean.css, src/static/common/css/common.css, src/templates/admin/core/manager/settings/group.html, src/themes/OLH/assets/js/table_of_contents.js, src/themes/OLH/assets/scss/app.scss, src/themes/OLH/templates/elements/journal/table_modal.html, src/themes/OLH/templates/journal/article.html, src/themes/clean/assets/css/clean.css, src/themes/clean/templates/elements/journal/table_modal.html, src/themes/clean/templates/journal/article.html, src/themes/material/assets/mat.css, src/themes/material/templates/elements/journal/table_modal.html, src/themes/material/templates/journal/article.html, src/transform/xsl/default.xsl
=> Jats tables

src/themes/OLH/templates/core/news/index.html, src/themes/OLH/templates/core/news/item.html, src/themes/OLH/templates/press/core/news/index.html, src/themes/material/templates/core/news/item.html, src/themes/material/templates/press/core/news/item.html
No issue for this but reported on freshdesk.
=> Remove success class from buttons

src/static/admin/css/admin.css, src/templates/admin/journal/document_management.html
- Adds a class for wrapping td contents.
- Adds class to tds containing user inputted info (label and filename)
- Closes #2652
=> #2652 added css to break the contents of these TDs

docs/source/conf.py
Updated the version number from 1.3.10 to 1.4.0
=> Changed the version number.

src/templates/admin/core/nav.html, src/templates/admin/elements/core/author_dashboard.html, src/templates/admin/journal/submissions.html
- Hides the submission link on various templates
- Closes #2567
=> #2567 hide submission links when submission is disabled.

src/transform/xsl/default.xsl
- Matches `bio//title` and wraps it in an `<h2>`
- Closes #2595
=> #2595 added he for <bio><title>

src/core/include_urls.py, src/core/logic.py, src/core/tests/test_logic.py, src/core/views.py, src/press/views.py, src/templates/admin/core/manager/index.html, src/templates/admin/elements/forms/group_journal.html, src/utils/install/journal_defaults.json
=> Add support email settings for manager page

src/themes/OLH/templates/cms/page.html, src/themes/clean/templates/cms/page.html, src/themes/material/templates/cms/page.html
The material theme already had an id on the CMS container. I added one for the title field and updated the two other themes as well to allow CSS customisations
=> Adds an id to the cms container on all themes

src/review/forms.py
- Checks if there is an assignment
- Catches when there is no ReviewAssignmentAnswer
- Closes #2671 
- Closes #2672
=> #2671 #2672 fixes both these bugs.

src/journal/models.py, src/themes/OLH/templates/press/press_journals.html
They will render a link to the issues page if they have any instead
=> Removes link from journals with no current issue

src/templates/admin/preprints/dashboard.html
Ref: https://github.com/BirkbeckCTP/janeway/issues/2694 
Standardises w/ language under "Incomplete Preprints"
=> Update author dashboard messaging

src/templates/admin/core/base.html
We forgot to include this on 1.4.0
=> Render django-hijack banner when DEBUG is False

src/transform/xsl/default.xsl
- Removes P tags that wrap references
- Closes #2585
=> #2585 removed excess <p> tags.

src/templates/admin/repository/article.html, src/templates/admin/repository/author_article.html
Ref: https://github.com/BirkbeckCTP/janeway/issues/2668
=> Fix DOI links in dashboard view

src/core/logic.py, src/press/views.py, src/templates/admin/press/press_manager_index.html
=> Add default journal support message to press manager view and template

src/themes/OLH/assets/scss/app.scss
=> #2581 make drilldown scrollable

src/themes/OLH/templates/elements/journal/article_filter_form.html, src/themes/OLH/templates/elements/journal/box_article.html, src/themes/OLH/templates/elements/journal/issue_sidebar.html, src/themes/OLH/templates/elements/journal/search_form.html, src/themes/OLH/templates/journal/article.html, src/themes/OLH/templates/journal/articles.html, src/themes/OLH/templates/journal/issue_display.html, src/themes/OLH/templates/journal/search.html
=> #2718 added fixes to sidebars

src/themes/OLH/assets/scss/app.scss, src/themes/OLH/templates/journal/homepage_elements/about.html, src/themes/OLH/templates/journal/index.html, src/themes/clean/templates/journal/index.html, src/themes/material/templates/journal/index.html
- Adds a general wrapper and a per element wrapper.
- moves about HPE inline styling to the new wrapper
=> Added a wrapper div to Homepage elements for custom styling

src/utils/install/journal_defaults.json, src/utils/notify_plugins/notify_email.py
=> Adds Custom Reply To address for system emails

src/journal/models.py, src/journal/tests/test_models.py
=> Fix domain journal url rendering while in browsing from path

src/cron/management/commands/send_reminders.py, src/cron/tests/test_commands.py, src/cron/tests/test_models.py, src/utils/testing/helpers.py
=> Fix bug so that reminders are sent properly

src/static/common/js/journal_filter.js, src/themes/OLH/templates/press/press_journals.html, src/themes/clean/assets/css/clean.css, src/themes/clean/templates/core/base.html, src/themes/clean/templates/core/footer.html, src/themes/clean/templates/elements/press_footer.html, src/themes/clean/templates/journal/homepage_elements/journals.html, src/themes/clean/templates/press/nav.html, src/themes/clean/templates/press/press_journals.html, src/themes/material/assets/mat.css, src/themes/material/templates/journal/homepage_elements/journals.html, src/themes/material/templates/press/elements/press_footer.html, src/themes/material/templates/press/nav.html, src/themes/material/templates/press/press_journals.html
- Fixes homepages
- Adds press_journals.html to both
- Moves filter script to commons/js
- Closes #1035
=> #1035 updates clean and material to work as press themes! YAY!

docs/source/manager/submission/index.rst, src/core/logic.py, src/submission/views.py, src/templates/admin/elements/forms/group_submission.html, src/templates/admin/elements/submit/file.html, src/templates/admin/submission/submit_files.html, src/utils/install/journal_defaults.json
See also https://github.com/BirkbeckCTP/janeway/issues/2496
=> #2550 Let editors change text in file submission pop-up windows

src/themes/OLH/assets/scss/app.scss
- Adds missing table wrapper overlflow
- Checked material and clean, both unaffected
- Closes #2800
=> #2800 added overflow for table wrapper.

docs/source/styling/image_guidelines.rst
Updated docs for issue/collection images.
=> #2749 updated docs

src/cron/models.py, src/cron/tests/test_models.py, src/utils/testing/helpers.py
=> items_for_reminder now filters Review and Revision objects by journal

src/api/oai/views.py
Currently, test journal articles are being exposed at the press level OAI feed.
=> OAI: Ensure hidden journals are not shared at the press level

src/submission/models.py, src/submission/tests.py
=> Replace HTML entities for their unicode counterparts on article.issue_title

src/themes/clean/assets/css/clean.css, src/themes/clean/templates/journal/article.html, src/themes/material/assets/mat.css
- Adds ToC
- Better table display
- Scales images
- Closes #2854
=> 2852 updates to bring the clean theme article page inline with OLH and material

src/api/serializers.py, src/api/urls.py, src/api/views.py, src/press/views.py, src/templates/admin/elements/merge_users.html, src/templates/admin/press/merge_users.html
- Updates the Account API endpoint
- Adds searching on Email, Fname and Lname
- Removes datatables and searches via the API endpoint for accounts
- Closes #2649
=> #2649 merge users page now uses the API to search and runs faster

src/api/oai/views.py, src/api/tests/test_oai.py
Turns out the set filters where overriding my pretty filtering applied by underlying mixins :(
=> Fix OAI not filtering by from/until

src/repository/logic.py, src/repository/views.py
=> 2869 adds additional filters to limit the scope of views to the current repository where required

src/static/common/css/common.css, src/transform/xsl/default.xsl
=> #2744 fixed list types and added jats title list type

src/themes/material/assets/mat.css
=> #2862 material theme: the font weight for <strong> tags is now heavier to show difference from normal text

src/utils/transactional_emails.py
=> Fix wrong copyeditor decision sent on notifications

src/submission/models.py
=> Fixed a server error when deleting duplicate frozen authors

src/review/views.py
=> Remove warning about non-public declined review assignments

src/themes/OLH/templates/elements/journal/preprint_article_listing.html, src/themes/OLH/templates/journal/authors.html, src/themes/OLH/templates/journal/editorial_team.html, src/themes/OLH/templates/repository/editors.html, src/themes/clean/templates/journal/editorial_team.html, src/themes/material/assets/mat.css, src/themes/material/templates/journal/editorial_team.html
=> #2793 added eq-height to editorial team page.

src/core/views.py, src/templates/admin/core/kanban.html, src/templates/admin/elements/core/kanban/card.html
=> Removed duplicate kanban cards for production and proofing.

src/transform/xsl/default.xsl
=> Adds support for JATS continued-from. Credit to @mauromsl

src/core/logic.py, src/templates/admin/elements/forms/group_journal.html, src/templates/common/elements/analytics.html, src/themes/OLH/templates/core/base.html, src/themes/clean/templates/core/base.html, src/themes/material/templates/core/base.html, src/utils/install/journal_defaults.json
Adds support for GA4 which will fully replace UA in 2023.
=> Added GA Four support to all themes.

src/templates/admin/repository/dashboard.html
Now updating the correct file
Follow up to: https://github.com/BirkbeckCTP/janeway/pull/2695
=> Updating the author dashboard text: owner->submitting author

src/templates/admin/journal/send_user_email.html
=> #2518 popup email windows now support attachments

src/core/templatetags/itertools.py, src/templates/admin/elements/review/review_block.html, src/templates/admin/review/in_review.html
=> Fix dropdown from overflowing the screen in review page

src/themes/clean/templates/elements/journal/authors_block.html, src/themes/material/templates/elements/article_listing.html
It was only missing in clean and material themes
=> Adds missing translation tags for the text 'and'

jenkins/entrypoint.sh, requirements.txt, src/core/locales/de/LC_MESSAGES/django.po, src/core/locales/nl/LC_MESSAGES/django.po, src/core/middleware.py, src/core/model_utils.py, src/core/models.py, src/journal/views.py, src/submission/models.py, src/themes/material/templates/journal/full-text-search.html
=> Fixes various issues noted with 1.4.2-RC-1

src/identifiers/logic.py, src/identifiers/tests/test_logic.py
Fixes to known issues to Janeway v1.4.2-RC-2
=> #2948 Fix bug that threw stage assignment on acceptance

docs/source/manager/identifiers/index.rst, src/core/logic.py, src/core/views.py, src/static/admin/css/admin.css, src/templates/admin/core/manager/identifier_manager.html, src/utils/install/journal_defaults.json
Addresses #2966 partially by preventing users from running big DOI batches.
=> Disable DOI Manager action buttons if too many articles

src/core/logic.py, src/templates/admin/elements/forms/group_journal.html, src/themes/OLH/templates/core/accounts/register.html, src/themes/clean/templates/core/accounts/register.html, src/themes/material/templates/core/accounts/register.html, src/utils/install/journal_defaults.json
=> 2971 Add custom message setting register_page_notice

docs/source/manager/identifiers/index.rst, src/identifiers/logic.py, src/identifiers/tests/test_logic.py, src/submission/models.py, src/templates/admin/review/decision.html, src/templates/common/identifiers/crossref_article.xml, src/utils/install/journal_defaults.json
=> Anonymises articles during Crossref pre-registration

src/templates/admin/repository/review/manage_review.html
=> #2994 adds href to the manage reviewers link on the add reviewer page.

src/templates/admin/repository/review/manage_review.html
=> Fixes a broken link to manage reviewers when adding a preprint reviewer

src/journal/forms.py, src/journal/logic.py
=> Ensure full-text search always has filters toggled

src/submission/models.py, src/templates/admin/elements/copyediting/complete_copyediting.html
=> #2847 replace hard coded next stage text when completing copyediting with calculation of next stage.

src/core/forms.py, src/core/logic.py, src/journal/forms.py, src/journal/logic.py, src/journal/views.py, src/repository/urls.py, src/repository/views.py, src/templates/admin/repository/article.html
=> 2936 ported popup email logic and form to core and added view to repositories so managers can email preprint owners from inside Janeway.

src/themes/OLH/templates/journal/article.html
=> #2320 the OLH theme will now display text when an article is not peer reviewed.

src/core/forms.py, src/journal/migrations/0018_journal_disable_html_downloads.py, src/journal/models.py, src/journal/views.py, src/templates/admin/elements/forms/group_article.html, src/themes/material/templates/journal/article.html
- Adds the existing setting to the Article settings page
- Moves exclude logic to the view, after render content is retrieved
- Closes #2840
=> #2840 added setting to form, updated to work on form.

src/themes/OLH/templates/core/accounts/register.html, src/themes/OLH/templates/core/accounts/reset_password.html, src/themes/clean/templates/core/accounts/register.html, src/themes/clean/templates/core/accounts/reset_password.html, src/themes/material/templates/core/accounts/register.html, src/themes/material/templates/core/accounts/reset_password.html
- Change markup in register and reset_password to better facilitate translations
=> Make the translation markup changes identified in PR #2974

src/copyediting/views.py, src/core/logic.py, src/core/templatetags/nose_tools.py, src/core/views.py, src/review/views.py, src/security/decorators.py, src/security/templatetags/securitytags.py, src/templates/admin/core/active_submissions.html, src/templates/admin/core/nav.html, src/templates/admin/review/home.html
=> Let section editors see more list views

src/themes/OLH/templates/elements/accounts/user_form.html, src/themes/clean/templates/elements/accounts/user_form.html, src/themes/material/templates/elements/accounts/user_form.html
=> #3063 remove the enable_digest field from themes as not all themes fail gracefully

src/core/include_urls.py, src/journal/models.py, src/press/forms.py, src/press/views.py, src/templates/admin/press/edit_press_journal_description.html, src/templates/admin/press/press_manager_index.html, src/themes/OLH/templates/press/press_journals.html, src/themes/clean/templates/press/press_journals.html, src/themes/material/templates/press/press_journals.html, src/utils/install/journal_defaults.json
=> #3112 allows staff to override the journal description when displaying it on the press journal list page.

src/journal/models.py, src/themes/OLH/templates/journal/article.html, src/themes/clean/templates/journal/article.html, src/themes/material/templates/journal/article.html
=> #3038 when the keywords page is enabled, readers can click on article keywords to see a list of articles that use that keyword.

src/submission/forms.py, src/templates/admin/elements/metadata.html, src/templates/admin/submission/edit/metadata.html
=> #2755 added the Article Rights field to the View and Edit metadata pages.

src/templates/admin/review/decision.html
Closes #2814 (sort of, the issue itself is not reproducable anymore but this helps)
=> #2814 updated the decision page's skip button text to make it clearer.

src/core/logic.py, src/templates/admin/elements/forms/group_submission.html, src/templates/admin/journal/submissions.html, src/themes/OLH/templates/journal/submissions.html, src/themes/clean/templates/journal/submissions.html, src/themes/material/templates/journal/submissions.html, src/utils/install/journal_defaults.json
=> #2857 when a journal disables submission they can now set a custom message.

src/themes/material/templates/elements/journal/issue_top.html
=> #2851 added link to toc header for material.

src/submission/decorators.py
=> #2969 staff, editors and section editors can bypass funding_is_enabled decorator

src/api/serializers.py, src/copyediting/forms.py, src/copyediting/views.py, src/core/forms.py, src/repository/forms.py, src/review/forms.py, src/review/tests.py, src/review/views.py, src/submission/forms.py, src/templates/admin/copyediting/add_copyeditor_assignment.html, src/templates/admin/copyediting/editor_review.html, src/templates/admin/elements/confirm_modal.html, src/templates/admin/review/add_review_assignment.html, src/templates/admin/review/revision/request_revisions.html
=> Editors will be warned when they attempt to assign a task to a user whose account is not active.

src/press/migrations/0014_auto_20171127_1502.py, src/press/models.py, src/themes/OLH/templates/elements/journal/box_article.html, src/themes/clean/templates/core/accounts/public_profile.html, src/themes/clean/templates/elements/article_listing.html, src/themes/material/templates/elements/article_listing.html
=> 2841 fixes article links on profile pages

src/transform/xsl/default.xsl
=> Fixed a bug preventing output of internal links to references from footnotes via XSLT

src/static/admin/css/app.css
=> Standardize admin fonts to Open Sans

src/identifiers/models.py, src/repository/forms.py, src/repository/views.py
=> 2937 adds DOI pattern validation to repository submission and update.

src/repository/forms.py, src/repository/urls.py, src/repository/views.py, src/themes/OLH/templates/repository/home.html, src/themes/OLH/templates/repository/list.html, src/themes/material/templates/repository/elements/subject_tree.html
=> 2935 various multitenancy bugfixes for repositories

src/submission/models.py, src/templates/admin/review/decision.html, src/templates/admin/review/in_review.html
=> #2819 adds description to Review Files block to avoid confusion and adds the latest manuscript and figure files inline below a revision request.

src/api/oai/views.py, src/api/tests/test_preprint_oai.py, src/core/templatetags/fqdn.py, src/templates/common/apis/OAI_GetRecord.xml, src/templates/common/apis/OAI_ListIdentifiers.xml, src/templates/common/apis/OAI_ListRecords.xml, src/templates/common/apis/OAI_PreprintIdentify.xml, src/templates/common/apis/OAI_base.xml, src/templates/common/apis/OAI_preprint_record.xml, src/templates/common/apis/OAI_preprint_record_header.xml, src/templates/common/apis/OAI_preprint_record_jats_stub.xml
When users go to OAI-PMH endpoints for preprint repositories respond with appropriate preprint articles and metadata.
=> #2875 oai pmh endpoint for preprints

src/themes/material/templates/journal/issues.html
=> Fix bug that duplicated issue title

src/templates/admin/repository/article.html, src/templates/admin/repository/review/edit_review_comment.html, src/templates/admin/repository/review/list_reviews.html, src/templates/admin/repository/review/manage_review.html, src/templates/admin/repository/review/notify_reviewer.html, src/templates/admin/repository/review/review_detail.html, src/themes/material/templates/repository/preprint.html
- Tries to make the wording of invited review comments similar throughout frontend and back end
- Note: Have left translation tags off on purpose here, I don't want to introduce these to translators at the moment
- Closes #3155 and Closes #3086
=> Updates for #3155 and #3086

src/templates/admin/submission/edit/metadata.html
This looks like a big diff but the main changes were focused on the funder search bar. While fixing it, I noticed the div nesting was messed up, so I debugged that by standardizing indentation levels. See this diff for actual changes:
```diff
diff --git a/src/templates/admin/submission/edit/metadata.html b/src/templates/admin/submission/edit/metadata.html
index 9c471323..bfdc04f4 100644
--- a/src/templates/admin/submission/edit/metadata.html
+++ b/src/templates/admin/submission/edit/metadata.html
@@ -117,6 +117,7 @@
</div>
</div>
</form>
+        </div>
<div class="title-area">
<h2>Authors</h2>
<a href="#" class="button" data-open="author">Add Author</a>
@@ -161,23 +162,43 @@
</tbody>
</table>
</form>
+        </div>
<div class="title-area">
<h2>Funding</h2>
</div>
<div class="content …
```
=> #3159 Fix bug that removed author when searching funders

src/utils/notify_plugins/notify_email.py
=> #3171 adds an email sent message whenever an email has a request and request.user object

docs/source/changelog.rst
=> Added changelog

src/core/include_urls.py
Contributes to BirkbeckCTP/consortial_billing#23.
=> Make plugin loading error messages more verbose

src/core/model_utils.py
=> Remove duplicated model utility classes

src/templates/admin/review/home.html
=> Fix bug that hid “My Assignments” in Articles in Review

src/themes/material/templates/repository/preprint.html
=> #3218 removes citation popups from preprint pages.

src/cms/models.py, src/themes/OLH/templates/elements/nav_element.html, src/themes/OLH/templates/press/nav.html, src/themes/clean/templates/elements/nav_element.html, src/themes/material/templates/elements/nav_element.html
=> Fix bug that caused broken link on OLH press nav

src/themes/OLH/templates/journal/article.html, src/themes/material/templates/journal/article.html
=> Fix bug that caused empty “Peer Review” heading in sidebar

src/templates/admin/core/active_submissions.html
=> Fix bug that let submission editors see other articles in Search Submissions

src/identifiers/logic.py, src/identifiers/views.py, src/templates/admin/identifiers/article_identifiers.html
=> Fix bugs with DOI registration status

docs/source/configuration.rst
=> Adds documentation on logging configuration

src/core/views.py, src/submission/models.py
- Updates the active_submissions view to use the active_submissions Article manager.
- Closes #3311
=> #3311 the Active Submissions view will no longer show archived articles.

src/transform/xsl/default.xsl
=> XSLT now allows ref/label nodes to be rendered as HTML

docs/source/editor/review.rst, docs/source/manager/review/index.rst, src/core/migrations/0078_anonymous_review_rewording.py, src/review/migrations/0003_auto_20180614_1039.py, src/review/models.py, src/templates/admin/review/add_files.html, src/utils/install/journal_defaults.json
=> Changes ableist terminology around peer review anonimity

src/submission/models.py, src/templates/admin/review/in_review.html
=> Fixed a bug where the review page suggested moving an article to the next stage incorrectly

src/review/models.py
=> #3326 fix query to get the latest round number

src/rss/urls.py, src/rss/views.py
=> 2498 - Add RSS feed for preprints

src/submission/models.py
Requested in ticket 6382
closes #3402
=> Fixed an issue where articles with a publication title override where not using in the "how to cite" block

requirements.txt, src/cms/logic.py, src/cms/management/commands/delete_site_search_index.py, src/cms/management/commands/generate_site_search_index.py, src/cms/models.py, src/cms/tests/test_site_search.py, src/core/janeway_global_settings.py, src/core/logic.py, src/core/middleware.py, src/core/tests/test_middleware.py, src/cron/management/commands/install_cron.py, src/utils/management/commands/generate_site_search_index.py, src/utils/management/commands/install_janeway.py, src/utils/testing/helpers.py
=> Build lunr site search index on server side

src/api/oai/base.py
Rolls back a change that made incoming dates timezone aware.
=> Oai datetime support

src/utils/notify_plugins/notify_email.py
=> Fix import error that happens on Python 3.10

src/cron/management/commands/install_cron.py
=> Fix crontab configuration bug

src/submission/admin.py, src/submission/forms.py, src/submission/models.py, src/submission/views.py, src/templates/admin/elements/fundref/fundref.html, src/templates/admin/elements/metadata.html, src/templates/admin/submission/edit/metadata.html, src/templates/admin/submission/submit_funding.html, src/themes/OLH/templates/journal/article.html, src/themes/clean/templates/journal/article.html, src/themes/material/templates/journal/article.html, src/utils/admin_utils.py
=> Funder form fixes

src/api/serializers.py, src/core/views.py, src/templates/admin/core/manager/users/enrol_users.html
- Allows staff to assign the journal manager role through Enrol Users
- Improves error message display
- Closes #3463
=> #3463 allows staff to assign the journal-manager role.

src/utils/notify_plugins/notify_email.py
=> Fix value error sanitize email extra

src/transform/xsl/default.xsl
These can be used to further style any piece of text arbitrarily
=> [XSLT] Allows styled-content to declare custom CSS classes

src/transform/xsl/default.xsl
=> Adds support for fig/alt-text to JATS XSLT

README.md
=> Fixes a typo in our Readme file

src/core/janeway_global_settings.py, src/utils/sessions/janeway_db.py
- Adds a new `SessionStore`
- Overrides `clear_expired` with a `transaction.atomic` decorator
- Does nothing else
=> Added a janeway db bases SessionStore and overwrite clear_expired

src/core/include_urls.py, src/themes/material/templates/journal/issues.html, src/utils/notify_helpers.py
- Updates the send email with template so that it supports plugins.
=> Updates the send email with template function to support plugins

requirements.txt, src/repository/management/commands/generate_preprints.py, src/themes/material/templates/repository/preprint.html
- Adds faker to requirements
- Updates the `generate_preprints` command
- Tweaked preprint.html display when no file is found for a given preprint
- Closes #3288
=> #3288 update generate_preprints command and tweaked preprint.html.

src/journal/views.py, src/submission/models.py
- The `journal.views` function `issue_add_articles` now uses the `Article` class' `active_objects` manager.
- Closes #3188
=> #3188 issue_add_articles now uses the active_objects manager

src/templates/admin/elements/article_jump.html
=> #3533 the Logs, Documents and More dropdown now has a link directly to the Edit Metadata page

src/utils/plugins.py
- Required for https://github.com/BirkbeckCTP/reporting/issues/15
=> Adds a check_plugin_exists function to utils.plugins

src/submission/models.py, src/submission/tests.py
- Updates the Section model's __str__ method to remove the PK
- Closes #3289
=> #3289 remove ID from section __str__

src/themes/OLH/assets/scss/app.scss
=> Fix a SASS bug that unset default colors on OLH theme

src/core/admin.py, src/review/admin.py
=> Use raw ID fields for files in a few spots for quicker loading

src/review/forms.py, src/templates/admin/elements/review/draft_decisions_js.html, src/templates/admin/review/draft_decision.html
=> Fix bug that reloaded an email template without user confirming

src/themes/OLH/templates/elements/section_block.html, src/themes/clean/templates/elements/sections_block.html, src/themes/material/templates/elements/sections_display.html
=> Fix bug with section display on submissions page

src/api/tests/test_oai.py, src/templates/common/encoding/article_jats_1_2.xml
- Adds additional fields to the JATS XML inline with recommended practice
- Fixes bug that meant issue titles would not be in JATS
- Closes #3557
=> Updates the JATS 1.2 XML document with additional information

src/themes/OLH/templates/journal/article.html, src/themes/clean/templates/journal/article.html, src/themes/material/templates/journal/article.html
Fixes #3207 
See also https://github.com/BirkbeckCTP/typesetting/issues/148
=> Modify article pages for all themes to support proofing accuracy

src/submission/models.py
=> Uses Django's SQL compiler to sort FT search results

src/review/const.py, src/review/urls.py, src/review/views.py, src/security/decorators.py, src/security/test_security.py
- Passes the decision a user makes into the warning page so it can then redirect the user on an override
- Closes #1471
=> #1471 pass decisions through to the warning view so it can redirect the user properly

src/repository/logic.py, src/templates/admin/elements/repository/author_metrics_chart.html, src/templates/admin/repository/author_article.html
=> #3559 Author preprint metrics summary  accesses are now split into views and downloads across two charts.

src/review/models.py, src/review/tests.py, src/review/views.py
=> #3588 fixed a bug that stopped editors from withdrawing a review.

src/themes/material/assets/mat.css
=> Fix bug that kept small caps from being applied

src/review/views.py, src/submission/models.py
=> Snapshot and update authors on acceptance before deposit #2702

src/utils/management/commands/run_upgrade.py
=> Deprecate run_upgrade command 

src/themes/material/templates/press/nav.html
=> Fix invalid anchor tag #3697

src/templates/admin/press/press_manager_index.html
=> Add menu option for press-level media manager #3144

src/submission/migrations/0044_auto_20200526_1010.py
=> Modify funder help text in submission migrations

src/utils/install/journal_defaults.json, src/utils/transactional_emails.py
=> #3627 the email sent to editors when an author completes revisions is now a template and is logged correctly

src/cron/models.py
- Added log_dict to the reminder email
- Closes #3099
=> #3099 reminder emails are now logged

docs/source/changelog.rst, docs/source/editor/review.rst, src/core/migrations/0083_update_spelling.py, src/review/migrations/0003_auto_20180614_1039.py, src/review/models.py, src/utils/install/journal_defaults.json
=> #3604 Updated spelling of anonimity to anonymity.

src/press/views.py, src/templates/admin/press/press_manager_index.html
=> #3598 the press manager index no longer errors when an article is orphaned from its journal.

src/templates/admin/review/in_review.html
=> #3586 fixes the display of the Review Files section when there are no files and its widescreen display

src/themes/OLH/assets/js/table_of_contents.js, src/themes/material/assets/toc.js
=> Auto-generated table of contents for articles (TOCs) can now have HTML in them.

src/themes/OLH/templates/core/accounts/register.html, src/themes/clean/templates/core/accounts/register.html, src/themes/material/templates/core/accounts/register.html
=> Password length requirement is displayed properly on all themes.

src/core/forms.py, src/core/views.py, src/templates/admin/core/manager/settings/edit_setting.html
=> #3643 when editing a single setting using the edit_key view unchecking a boolean now works as expected.

src/core/include_urls.py, src/core/views.py
=> Fix article list view access

requirements.txt
=> Pin urllib3<2 due to compatibility issues with requests

src/themes/OLH/assets/scss/app.scss, src/themes/clean/assets/css/clean.css, src/themes/material/assets/mat.css
=> Apply scrollbar to long unbroken MathJax lines #3753

src/utils/orcid.py
=> Fix KeyError when logging with orcid and name is not publicly available

src/journal/models.py, src/utils/management/commands/install_journal.py
=> 3705 Adds a signal that will create a directory in src/files when a new journal is created.

src/copyediting/forms.py, src/copyediting/views.py, src/templates/admin/copyediting/edit_assignment.html
=> #3728 editing a copyedit assignment will now success and, if it fails, it will disply an error.

src/templates/admin/review/unassigned_article.html
=> Adds an edit metadata button to the unassigned article/editor assignment page.

src/security/decorators.py
=> Include GET parameters when redirecting after login #3701

src/utils/notify_plugins/notify_email.py
=> #3731 mailbox labels are now wrapped in quotes and sanitize_from is appllied to journal and user names

src/templates/admin/repository/comments.html
- Adds linebreaksbr to the backend display of repository comments so they display properly
=> Repository comments will now display properly in the manager interface

src/static/common/css/repo.css, src/themes/material/templates/repository/preprint.html
Discussed showing only headers and expanding with ULBD and INGGRID but decided allowing a larger space for comments would be the best approach.
- Closes #3423
=> #3423 moved comments box under preprint iframe.

.update.sh, Makefile, docs/source/changelog.rst, docs/source/conf.py, src/api/tests/test_oai.py, src/cms/migrations/0015_historicalpage.py, src/comms/migrations/0005_historicalnewsitem.py, src/core/locales/de/LC_MESSAGES/django.po, src/core/locales/en_us/LC_MESSAGES/django.po, src/core/locales/fr/LC_MESSAGES/django.po, src/core/locales/it/LC_MESSAGES/django.po, src/core/locales/nl/LC_MESSAGES/django.po, src/core/logic.py, src/janeway/__init__.py, src/repository/migrations/0037_historicalrepository.py, src/templates/common/encoding/article_jats_1_2.xml, src/utils/logic.py, src/utils/migrations/0031_upgrade_1_5_1.py
Fixes invalid JATS XML template for OAI feed
Fixes #3786
=> v1.5.1 RC 1 fixes

src/templates/admin/review/home.html
=> Close a <tr> left open

src/utils/install/journal_defaults.json
Fixed typo in 'EDIT PROOFREADER ASSIGNMENT NOTIFICATION (PLUGIN) (TYPESETTING_NOTIFY_PROOFREADER)'. 'An notification' to 'a notification'
=> Update journal_defaults.json - typofix1

src/core/homepage_elements/news/forms.py, src/core/homepage_elements/news/hooks.py, src/core/homepage_elements/news/plugin_settings.py, src/core/homepage_elements/news/templates/news_settings.html, src/core/homepage_elements/news/views.py, src/themes/OLH/templates/journal/homepage_elements/news.html, src/themes/material/templates/journal/homepage_elements/news.html
=> 3672 adds a new setting to the news homepage element to allow the display of images, works for OLH and Material themes.

src/themes/OLH/templates/journal/editorial_team.html
=> #3673 when creating a new row include the data-equalizer to ensure that blocks are the same height.

requirements.txt, src/utils/install/journal_defaults.json, src/utils/management/commands/send_email.py
=> Management command for sending emails

src/core/forms/forms.py
=> Remove superseded class definition

src/cms/forms.py, src/core/forms/forms.py, src/press/forms.py
=> Remove required from some form BleachFields

src/themes/material/templates/core/homepage_elements/search_bar.html
=> #3872 search bar label for now matches the search field ID

src/repository/views.py
=> #3877 when searching repoistory objects by author results are now limited by repository.

src/journal/views.py
=> #3883 the journal article page is now sorted correctly by default

src/review/forms.py, src/review/views.py, src/templates/admin/review/manager/preview_form.html
=> #3888 Updated the preview peer review form to hide the open peer review section when setting is disabled.

src/journal/views.py, src/templates/admin/elements/journal/log_description.html
=> #3873 request.FILES now passed to EmailForm when sending a user email.

src/core/workflow.py, src/review/logic.py, src/review/views.py, src/templates/admin/elements/email_form.html, src/utils/tests.py, src/utils/transactional_emails.py
- Update `review.logic.assign_editor` so that it works as it should
- Closes #3866
=> #3866 automatic editor assignments now fire as expected

src/core/templatetags/fqdn.py, src/templates/common/elements/social_meta.html
=> Improvements to meta tags #3692

dev-requirements.txt, docs/source/configuration.rst, src/core/urls.py
=> Allow configuration of django-browser-reload

src/utils/install/journal_defaults.json
=> Add setting for external newsletter signup URL

src/press/models.py
=> Convenience methods on press object #3707

src/cms/views.py
=> Fix custom template path calculation

src/comms/views.py
I updated the tag query to get the object or raise 404.
=> #3949 bugfix - update getting tag object in news_list() func

src/core/locales/cy/LC_MESSAGES/django.po, src/core/locales/de/LC_MESSAGES/django.po, src/core/locales/en_us/LC_MESSAGES/django.po, src/core/locales/es/LC_MESSAGES/django.po, src/core/locales/fr/LC_MESSAGES/django.po, src/core/locales/it/LC_MESSAGES/django.po, src/core/locales/nl/LC_MESSAGES/django.po, src/core/views.py, src/themes/OLH/templates/elements/journal_footer.html, src/themes/clean/templates/elements/journal_footer.html, src/themes/material/templates/elements/journal_footer.html
=> Flags more public strings for translation

src/journal/views.py
=> Fixed a bug where PDF/XML article files could be downloaded before an article is published

src/core/admin.py
=> You can search by user ID in the admin interface

src/templates/common/elements/altmetric_badges.html
=> #3676 added data-hide-no-mentions tag

src/templates/admin/review/unassigned.html
=> Adds datatables to the unassigned articles list page by default they are now sorted by date submitted, ascending.

src/core/views.py, src/templates/admin/core/manager/roles/role.html
Closes #3039 
- Adds additional information when viewing the list of reviewers
- Also enhances the standard view with history and edit buttons
- This page also now loads much faster, with queries reduced from >2000 to <500.
=> Enhances the reviewer role list with additional, reviewer specific detail.

src/themes/OLH/templates/repository/preprint.html
=> Updates the OLH theme to ensure user images are not displayed on anonymous reviews.

src/themes/OLH/assets/foundation-sites/js/foundation.reveal.js
=> #3922 remove aria-haspopup from reveal

src/core/email.py, src/journal/logic.py
=> #3810 fixes a bug where action_text was not being recorded for two email types

src/templates/admin/copyediting/copyediting.html
added article accepted date to copyediting dashboard table.
Closes #2296
=> #2296 acceptance date added to copyediting dashboard table

src/core/janeway_global_settings.py
=> Fixed a bug where URLS entered into rich-text editors would automatically be transformed into relative urls

src/repository/views.py
=> #3897 Repository searches now exclude extraneous white space

src/templates/admin/core/nav.html
=> Janeway version is visible to everyone

src/templates/admin/core/workflow.html, src/templates/admin/journal/article_log.html, src/templates/admin/journal/manage/publication_schedule.html, src/templates/admin/review/unassigned.html, src/templates/admin/submission/start.html, src/templates/admin/submission/submit_authors.html, src/templates/admin/submission/submit_files.html, src/templates/admin/submission/submit_funding.html, src/templates/admin/submission/submit_info.html, src/templates/admin/submission/submit_review.html
added basic breadcrumbs to the templates as shown in the commits.  One commit per section.
Closes #3858
=> 3858 missing breadcrumb fix

src/templates/admin/review/unassigned.html
duplicate introduced in error.
=> #4155 removing duplicate breadcrumb block

src/templates/admin/review/revision/view_revision.html
Kinda self explanatory this one.
=> Fixes a bad typo on the editor's revision interface.

src/review/logic.py, src/review/views.py, src/templates/admin/elements/datatables.html, src/templates/admin/elements/review/add_reviewer_table_row.html, src/templates/admin/review/add_review_assignment.html
This is a port of #4101 for `release_1_5_x`
=> Reviewers from past review rounds are now valid review assignment choices

src/journal/urls.py, src/transform/urls.py
updated the 3 specified url patterns as per issue
Closes #3776
=> #3776 specified url patterns updated from .+ to \d+

src/journal/views.py
=> When sending a direct email to a user this message is now logged

src/core/logic.py, src/templates/admin/elements/forms/group_editorial.html, src/templates/common/elements/journal/editorial_team_country.html, src/themes/OLH/templates/journal/editorial_team.html, src/themes/clean/templates/journal/editorial_team.html, src/themes/material/templates/journal/editorial_team.html, src/utils/install/journal_defaults.json
=> Adds an option to display country after affiliation on editorial team pages

src/repository/migrations/0044_historicalrepository_review_submission_text_and_more.py, src/repository/migrations/0045_historicalrepository_display_public_metrics_and_more.py
=> Fix repository migration conflict

src/core/logic.py
=> Fix a bug that kept support email and message from displaying in journal settings

src/core/include_urls.py, src/core/views.py, src/journal/views.py, src/press/views.py, src/repository/views.py, src/static/common/xslt/sitemap.xsl, src/templates/common/journal_sitemap.xml, src/templates/common/repo_sitemap.xml, src/utils/tests.py
=> Adds support for repository sitemaps.

src/core/locales/nl/LC_MESSAGES/django.po
=> Add Dutch translation for copyright help text 

src/templates/admin/elements/review/review_block.html, src/templates/admin/elements/review/reviews_small.html
=> Fixed an issue where review decisions where sometimes displayed to editors before the review assignment was completed.

src/utils/install/journal_defaults.json, src/utils/migrations/0036_typesetting_guide.py
Completes https://github.com/openlibhums/typesetting/pull/219
=> Update typesetting guide

docs/source/dev.rst, docs/source/dev/pii.rst, docs/source/editor/review.rst
=> Added documentation for the triple anonymous peer review system

requirements.txt
=> Switches django-materializecss-form to our own fork with fix

src/core/forms/forms.py, src/core/views.py, src/journal/views.py
Fixes #4449. 
Note that installations running the isolinear plugin will also need https://github.com/openlibhums/isolinear/pull/4
=> Fix the item counts on the filters on the article search page

src/core/forms/forms.py, src/journal/tests/test_views.py, src/utils/testing/helpers.py
=> Fix and test article filter label counts

src/templates/admin/copyediting/author_review.html, src/templates/admin/copyediting/do_copyedit.html, src/templates/admin/copyediting/editor_review.html, src/templates/admin/copyediting/upload_file.html
Copy-edited to copyedited for consistency
=> spelling fix

src/themes/OLH/templates/elements/right_hand_menu.html, src/themes/material/templates/core/nav.html
=> Tha Kanban link will no longer show for non Editor users

src/themes/OLH/templates/core/accounts/activate_account.html, src/themes/OLH/templates/core/accounts/edit_profile.html, src/themes/OLH/templates/core/accounts/get_reset_token.html, src/themes/OLH/templates/core/accounts/orcid_registration.html, src/themes/OLH/templates/core/accounts/public_profile.html, src/themes/OLH/templates/core/accounts/register.html, src/themes/OLH/templates/core/accounts/reset_password.html, src/themes/clean/templates/core/accounts/activate_account.html, src/themes/clean/templates/core/accounts/edit_profile.html, src/themes/clean/templates/core/accounts/get_reset_token.html, src/themes/clean/templates/core/accounts/orcid_registration.html, src/themes/clean/templates/core/accounts/public_profile.html, src/themes/clean/templates/core/accounts/register.html, src/themes/clean/templates/core/accounts/reset_password.html, src/themes/material/templates/core/accounts/activate_account.html, src/themes/material/templates/core/accounts/edit_profile.html, src/themes/material/templates/core/accounts/get_reset_token.html, src/themes/material/templates/core/accounts/public_profile.html, src/themes/material/templates/core/accounts/register.html, src/themes/material/templates/core/accounts/reset_password.html
=> Fix error with extends in account templates

src/templates/admin/core/accounts/register.html
=> Fix regression where ORCID was not saved during registration

src/transform/xsl/default.xsl
Adds a test when rendering year after person group in element-citations.
Closes #4373
=> #4373 adds a test for ..//year when rendering element-citations.

src/templates/admin/core/accounts/edit_profile.html, src/templates/admin/core/accounts/login.html
=> Make sure breadcrumbs only appear when they are useful

src/templates/admin/elements/metadata.html
=> Fixes rendering of 'Comments to the Editor' on the metadata modal.

requirements.txt
=> Adjust a few dependencies for Python 3.12

src/themes/OLH/templates/core/nav.html
This change brings the OLH theme in line with material and clean.
=> Ensure submissions nav item is displayed even when submissions are disabled

src/repository/forms.py
=> Fix a bug that prevented preprint info page from loading

src/utils/transactional_emails.py
- Closes #4505 
(This is a clean branch from r-v1.7.x)
=> Updated prepub notifications description to use an f-string

src/themes/clean/assets/css/clean.css
=> bugfix clean blockquote styling

src/core/migrations/0104_location_organization_affiliation.py, src/core/models.py, src/utils/migrations/0041_rorimport_rorimporterror.py, src/utils/models.py
=> Add missing max_length to CharFields

src/templates/admin/elements/repository/version_detail.html
=> Updates version detail to use the correct backend download url route

src/templates/admin/journal/manage/published_article_archive.html, src/themes/OLH/templates/journal/homepage_elements/carousel.html, src/themes/OLH/templates/press/homepage_elements/journals_and_html.html
=> march minor fixes

src/templates/admin/core/manager/users/list.html
=> Add missing quote mark

src/themes/OLH/assets/scss/app.scss
=> bugfix a11y - OLH dyslexia mode text resize

src/copyediting/models.py, src/typesetting/models.py
=> Fixed a bug that prevented articles from being deleted via admin

docs/md/contributing-guide.md
=> Guide to contributing developer documentation

src/core/migrations/0104_location_organization_affiliation.py, src/core/model_utils.py, src/submission/migrations/0085_creditrecord_and_more.py
=> Fix a bug with constraint names that caused a database error during upgrade

src/core/views.py, src/templates/admin/core/kanban.html
=> Articles in Typesetting will now show in kanban as expected

src/core/janeway_global_settings.py, src/core/tests/test_model_utils.py, src/utils/management/commands/clean_up_amps.py
Fixes #4695.
Please see https://github.com/openlibhums/janeway/issues/4695#issuecomment-2782531749 for an explanation of the underlying issue.
=> Prevent recursive amps in bleach fields

src/templates/admin/elements/forms/group_journal_images.html
=> The journal images settings page now displays the correct default profile image

src/cms/views.py
=> Toggling Editorial Team or Keywords nav entries now displays changes immediately

src/templates/admin/elements/metadata.html, src/templates/admin/review/unassigned_article.html, src/templates/admin/submission/edit/metadata.html, src/themes/material/templates/journal/article.html, src/typesetting/templates/typesetting/elements/typesetter/metadata.html
=> display author CRediT in back-office workflow

src/review/forms.py, src/submission/forms.py, src/submission/tests.py, src/templates/admin/elements/generate_form.html, src/utils/testing/helpers.py
=> Submission fields can now be unchcked. Review form checkboxes now display labels.

src/themes/clean/templates/core/nav.html, src/themes/material/templates/core/nav.html
=> fix missing nav items

src/core/migrations/0108_workflowlog_user.py
=> Fix migration for workflow log user

src/core/locales/es/LC_MESSAGES/django.po, src/core/locales/fr/LC_MESSAGES/django.po, src/core/migrations/0104_location_organization_affiliation.py, src/core/templatetags/hooks.py, src/journal/middleware.py, src/journal/views.py, src/submission/migrations/0008_auto_20170907_1159.py, src/submission/migrations/0034_auto_20190416_1009.py, src/submission/models.py, src/themes/OLH/templates/journal/article.html, src/themes/clean/templates/journal/article.html, src/themes/material/templates/journal/article.html, src/utils/management/commands/copy_settings.py
=> Merge of ILR-FLOW into r-v1.8.x

src/transform/xsl/default.xsl
=> A11y improvements for endnote backlinks

src/themes/OLH/templates/core/base.html, src/themes/material/templates/core/base.html
closes #4312 
and also closes openlibhums/books#54
=> a11y - language of page to change with translations

src/core/include_urls.py
=> Fixed an issue where 500 errors where returned when matching malformed orcid tokens

src/static/common/css/common.css, src/templates/common/elements/guest_editors.html, src/templates/common/elements/journal/article_authors_br.html, src/templates/common/repository/subject_display.html, src/themes/clean/assets/css/clean.css, src/themes/clean/templates/core/accounts/public_profile.html, src/themes/clean/templates/core/news/item.html, src/themes/clean/templates/elements/article_listing.html, src/themes/clean/templates/elements/journal/authors_block.html, src/themes/clean/templates/elements/journal/citation_modals.html, src/themes/clean/templates/elements/journal_footer.html, src/themes/clean/templates/elements/license_block.html, src/themes/clean/templates/elements/preprint_block.html, src/themes/clean/templates/journal/article.html, src/themes/clean/templates/journal/full-text-search.html, src/themes/clean/templates/journal/print.html, src/themes/clean/templates/journal/search.html, src/themes/clean/templates/press/core/news/item.html, src/themes/material/templates/elements/journal_footer.html
=> a11y clean - update loops to non-visible list syntax and style
